__all__ = (
    'LINKED_QUEST_COMPLETION_STATE_ACTIVE', 'LINKED_QUEST_COMPLETION_STATE_COMPLETED',
    'LINKED_QUEST_COMPLETION_STATE_NONE', 
)


LINKED_QUEST_COMPLETION_STATE_NONE = 0
LINKED_QUEST_COMPLETION_STATE_ACTIVE = 1
LINKED_QUEST_COMPLETION_STATE_COMPLETED = 2
