__all__ = (
    'QUEST_TEMPLATE_ID_MARISA_FLYKILLER_AMANATA', 'QUEST_TEMPLATE_ID_MYSTIA_CARROT',
    'QUEST_TEMPLATE_ID_MYSTIA_DEVILCART_OYSTER', 'QUEST_TEMPLATE_ID_MYSTIA_GARLIC', 'QUEST_TEMPLATE_ID_MYSTIA_PEACH',
    'QUEST_TEMPLATE_ID_MYSTIA_SCARLET_ONION', 'QUEST_TEMPLATE_ID_NONE', 'QUEST_TEMPLATE_ID_SAKUYA_BLUEBERRY',
    'QUEST_TEMPLATE_ID_SAKUYA_BLUEFRANKISH', 'QUEST_TEMPLATE_ID_SAKUYA_DEVILCART_OYSTER',
    'QUEST_TEMPLATE_ID_SAKUYA_STRAWBERRY',
)


QUEST_TEMPLATE_ID_NONE = 0
QUEST_TEMPLATE_ID_SAKUYA_STRAWBERRY = 1
QUEST_TEMPLATE_ID_MYSTIA_PEACH = 2
QUEST_TEMPLATE_ID_SAKUYA_BLUEBERRY = 3
QUEST_TEMPLATE_ID_MYSTIA_DEVILCART_OYSTER = 4
QUEST_TEMPLATE_ID_SAKUYA_DEVILCART_OYSTER = 5
QUEST_TEMPLATE_ID_MARISA_FLYKILLER_AMANATA = 6
QUEST_TEMPLATE_ID_SAKUYA_BLUEFRANKISH = 7
QUEST_TEMPLATE_ID_MYSTIA_CARROT = 8
QUEST_TEMPLATE_ID_MYSTIA_GARLIC = 9
QUEST_TEMPLATE_ID_MYSTIA_SCARLET_ONION = 10
