__all__ = (
    'QUEST_REWARD_TYPE_BALANCE', 'QUEST_REWARD_TYPE_CREDIBILITY', 'QUEST_REWARD_TYPE_ITEM_EXACT',
    'QUEST_REWARD_TYPE_NONE'
)


QUEST_REWARD_TYPE_NONE = 0
QUEST_REWARD_TYPE_BALANCE = 1
QUEST_REWARD_TYPE_CREDIBILITY = 2
QUEST_REWARD_TYPE_ITEM_EXACT = 3
