__all__ = (
    'QUEST_TEMPLATE_ID_ALICE_FLYKILLER_AMANITA', 'QUEST_TEMPLATE_ID_CHIRUNO_FROG', 'QUEST_TEMPLATE_ID_DAI_FROG',
    'QUEST_TEMPLATE_ID_JUNKO_ANGELROOT', 'QUEST_TEMPLATE_ID_KOISHI_ANGELROOT', 'QUEST_TEMPLATE_ID_KOISHI_BISHOPHAT',
    'QUEST_TEMPLATE_ID_KOISHI_GARLIC', 'QUEST_TEMPLATE_ID_KOISHI_RULER', 'QUEST_TEMPLATE_ID_KOKORO_SCISSORS',
    'QUEST_TEMPLATE_ID_MARISA_FLYKILLER_AMANITA',
    'QUEST_TEMPLATE_ID_MYSTIA_BAMBOO_SHOOT', 'QUEST_TEMPLATE_ID_MYSTIA_CARROT',
    'QUEST_TEMPLATE_ID_MYSTIA_DEVILCART_OYSTER', 'QUEST_TEMPLATE_ID_MYSTIA_GARLIC',
    'QUEST_TEMPLATE_ID_MYSTIA_PEACH', 'QUEST_TEMPLATE_ID_MYSTIA_SCARLET_ONION', 'QUEST_TEMPLATE_ID_NONE',
    'QUEST_TEMPLATE_ID_SAKUYA_BLUEBERRY', 'QUEST_TEMPLATE_ID_SAKUYA_BLUEFRANKISH',
    'QUEST_TEMPLATE_ID_SAKUYA_DEVILCART_OYSTER', 'QUEST_TEMPLATE_ID_SAKUYA_STRAWBERRY',
    'QUEST_TEMPLATE_ID_TEWI_BISHOPHAT', 'QUEST_TEMPLATE_ID_YUKARI_RULER', 'QUEST_TEMPLATE_ID_YUUKA_STRAW_HAT'
)


QUEST_TEMPLATE_ID_NONE = 0
QUEST_TEMPLATE_ID_SAKUYA_STRAWBERRY = 1
QUEST_TEMPLATE_ID_MYSTIA_PEACH = 2
QUEST_TEMPLATE_ID_SAKUYA_BLUEBERRY = 3
QUEST_TEMPLATE_ID_MYSTIA_DEVILCART_OYSTER = 4
QUEST_TEMPLATE_ID_SAKUYA_DEVILCART_OYSTER = 5
QUEST_TEMPLATE_ID_MARISA_FLYKILLER_AMANITA = 6
QUEST_TEMPLATE_ID_SAKUYA_BLUEFRANKISH = 7
QUEST_TEMPLATE_ID_MYSTIA_CARROT = 8
QUEST_TEMPLATE_ID_MYSTIA_GARLIC = 9
QUEST_TEMPLATE_ID_MYSTIA_SCARLET_ONION = 10
QUEST_TEMPLATE_ID_ALICE_FLYKILLER_AMANITA = 11
QUEST_TEMPLATE_ID_SAKUYA_FISHING_ROD = 12
QUEST_TEMPLATE_ID_CHIRUNO_FROG = 13
QUEST_TEMPLATE_ID_DAI_FROG = 14
QUEST_TEMPLATE_ID_TEWI_BISHOPHAT = 15
QUEST_TEMPLATE_ID_JUNKO_ANGELROOT = 16
QUEST_TEMPLATE_ID_KOISHI_ANGELROOT = 17
QUEST_TEMPLATE_ID_KOKORO_SCISSORS = 18
QUEST_TEMPLATE_ID_KOISHI_BISHOPHAT = 19
QUEST_TEMPLATE_ID_KOISHI_RULER = 20
QUEST_TEMPLATE_ID_YUKARI_RULER = 21
QUEST_TEMPLATE_ID_YUUKA_STRAW_HAT = 22
QUEST_TEMPLATE_ID_KOISHI_GARLIC = 23
QUEST_TEMPLATE_ID_MYSTIA_BAMBOO_SHOOT = 24
