__all__ = (
    'QUEST_REQUIREMENT_TYPE_DURATION', 'QUEST_REQUIREMENT_TYPE_EXPIRATION', 'QUEST_REQUIREMENT_TYPE_ITEM_CATEGORY',
    'QUEST_REQUIREMENT_TYPE_ITEM_EXACT', 'QUEST_REQUIREMENT_TYPE_ITEM_GROUP', 'QUEST_REQUIREMENT_TYPE_NONE',
)


QUEST_REQUIREMENT_TYPE_NONE = 0
QUEST_REQUIREMENT_TYPE_ITEM_EXACT = 1
QUEST_REQUIREMENT_TYPE_ITEM_GROUP = 2
QUEST_REQUIREMENT_TYPE_ITEM_CATEGORY = 3
QUEST_REQUIREMENT_TYPE_EXPIRATION = 4
QUEST_REQUIREMENT_TYPE_DURATION = 5
