__all__ = (
    'ADVENTURE_STATE_ACTIONING', 'ADVENTURE_STATE_CANCELLED', 'ADVENTURE_STATE_DEPARTING',
    'ADVENTURE_STATE_FINALIZED', 'ADVENTURE_STATE_RETURNING', 
)

ADVENTURE_STATE_DEPARTING = 1
ADVENTURE_STATE_ACTIONING = 2
ADVENTURE_STATE_RETURNING = 3
ADVENTURE_STATE_FINALIZED = 4
ADVENTURE_STATE_CANCELLED = 5
