__all__ = ('LOOT_STATE_LOST_DUE_FULL_INVENTORY', 'LOOT_STATE_LOST_DUE_LOW_ENERGY', 'LOOT_STATE_SUCCESS',)

LOOT_STATE_SUCCESS = 1
LOOT_STATE_LOST_DUE_LOW_ENERGY = 2
LOOT_STATE_LOST_DUE_FULL_INVENTORY = 3
