__all__ = ('MESSAGE_RENDER_MODE_CREATE', 'MESSAGE_RENDER_MODE_DELETE')

ROLE_MENTIONS_MAX = 20


DATE_TIME_CONDITION_ALL = 0
DATE_TIME_CONDITION_PAST = 1
DATE_TIME_CONDITION_FUTURE = 2

GUILD_PROFILE_RENDER_MODE_GENERAL = 0
GUILD_PROFILE_RENDER_MODE_JOIN = 1
GUILD_PROFILE_RENDER_MODE_LEAVE = 2

MENTIONED_USERS_MAX = 100
MENTIONED_ROLES_MAX = 100

VOTERS_MAX = 100

MESSAGE_RENDER_MODE_CREATE = 0
MESSAGE_RENDER_MODE_DELETE = 1
