__all__ = ()

ROLE_MENTIONS_MAX = 20


DATE_TIME_CONDITION_ALL = 0
DATE_TIME_CONDITION_PAST = 1
DATE_TIME_CONDITION_FUTURE = 2

GUILD_PROFILE_MODE_GENERAL = 0
GUILD_PROFILE_MODE_JOIN = 1
GUILD_PROFILE_MODE_LEAVE = 2
