__all__ = ('TOUHOU_SAFE_BOORU_TAGS',)

from .characters import (
    AKI_MINORIKO, AKI_SHIZUHA, CHEN, CHIRUNO, CLOWNPIECE, DAIYOUSEI, DOREMY_SWEET, EBISU_EIKA, ELLY, ETERNITY_LARVA, 
    FUJIWARA_NO_MOKOU, FUTATSUIWA_MAMIZOU, HAKUREI_REIMU, HANIYASUSHIN_KEIKI, HATA_NO_KOKORO, HEARN_MARIBEL, 
    HECATIA_LAPISLAZULI, HEI_MEILING, HIEDA_NO_AKYUU, HIJIRI_BYAKUREN, HIMEKAIDOU_HATATE, HIMEMUSHI_MOMOYO, 
    HINANAWI_TENSHI, HONG_MEILING, HORIKAWA_RAIKO, HOSHIGUMA_YUUGI, HOUJUU_NUE, HOURAISAN_KAGUYA, IBARAKI_KASEN, 
    IBUKI_SUIKA, IIZUNAMARU_MEGUMU, IMAIZUMI_KAGEROU, INABA_TEWI, INUBASHIRI_MOMIJI, IZAYOI_SAKUYA, JOUTOUGUU_MAYUMI, 
    JUNKO, KAENBYOU_RIN, KAGIYAMA_HINA, KAKU_SEIGA, KAMISHIRASAWA_KEINE, KASODANI_KYOUKO, KAWASHIRO_NITORI, 
    KAZAMI_YUUKA, KICCHOU_YACHIE, KIJIN_SEIJA, KIRISAME_MARISA, KISHIN_SAGUME, KISUME, KITASHIRAKAWA_CHIYURI, KOAKUMA, 
    KOCHIYA_SANAE, KOKUU_HARUTO, KOMANO_AUNN, KOMEIJI_KOISHI, KOMEIJI_SATORI, KONNGARA, KONPAKU_YOUMU, KUDAMAKI_TSUKASA, 
    KUMOI_ICHIRIN, KURODANI_YAMAME, KUROKOMA_SAKI, LETTY_WHITEROCK, LILY_WHITE, LUNASA_PRISMRIVER, LUNA_CHILD, 
    LYRICA_PRISMRIVER, MARGATROID_ALICE, MATARA_OKINA, MEDICINE_MELANCHOLY, MERLIN_PRISMRIVER, MIMA, MIYAKO_YOSHIKA, 
    MIZUHASHI_PARSEE, MONONOBE_NO_FUTO, MORICHIKA_RINNOSUKE, MORIYA_SUWAKO, MOTOORI_KOSUZU, MURASA_MINAMITSU, 
    MYSTIA_LORELEI, NAGAE_IKU, NAZRIN, NISHIDA_SATONO, NIWATARI_KUTAKA, OKUNODA_MIYOI, ONOZUKA_KOMACHI, 
    PATCHOULI_KNOWLEDGE, REISEN_UDONGEIN_INABA, REIUJI_UTSUHO, RINGO, RUMIA, SAIGYOUJI_YUYUKO, SAKATA_NEMUNO, 
    SCARLET_FLANDRE, SCARLET_REMILIA, SEIRAN, SEKIBANKI, SHAMEIMARU_AYA, SHIKI_EIKI_YAMAXANADU, STAR_SAPPHIRE, 
    SUKUNA_SHINMYOUMARU, SUNNY_MILK, TAMATSUKURI_MISUMARU, TATARA_KOGASA, TEIREIDA_MAI, TENKYUU_CHIMATA, TORAMARU_SHOU, 
    TOUTETSU_YUUMA, TOYOSATOMIMI_NO_MIKO, USAMI_RENKO, USAMI_SUMIREKO, USHIZAKI_URUMI, WAKASAGIHIME, 
    WATATSUKI_NO_TOYOHIME, WATATSUKI_NO_YORIHIME, WRIGGLE_NIGHTBUG, YAGOKORO_EIRIN, YAKUMO_RAN, YAKUMO_YUKARI, 
    YASAKA_KANAKO, YATADERA_NARUMI, YORIGAMI_JOON, YORIGAMI_SHION
)


TOUHOU_SAFE_BOORU_TAGS = {
    AKI_MINORIKO: ('aki_minoriko', ),
    AKI_SHIZUHA: ('aki_shizuha', ),
    LUNA_CHILD: ('luna_child', ),
    CHEN: ('chen', ),
    CHIRUNO: ('cirno', ),
    DAIYOUSEI: ('daiyousei', ),
    EBISU_EIKA: ('ebisu_eika', ),
    ELLY: ('elly', ),
    ETERNITY_LARVA: ('eternity_larva', ),
    FUJIWARA_NO_MOKOU: ('fujiwara_no_mokou', ),
    FUTATSUIWA_MAMIZOU: ('futatsuiwa_mamizou', ),
    HEARN_MARIBEL: ('maribel_hearn', ),
    HANIYASUSHIN_KEIKI: ('haniyasushin_keiki', ),
    HAKUREI_REIMU: ('hakurei_reimu', ),
    HATA_NO_KOKORO: ('hata_no_kokoro', ),
    HEI_MEILING: ('hei_meiling', ),
    HIEDA_NO_AKYUU: ('hieda_no_akyuu', ),
    HIJIRI_BYAKUREN: ('hijiri_byakuren', ),
    HIMEKAIDOU_HATATE: ('himekaidou_hatate', ),
    HIMEMUSHI_MOMOYO: ('himemushi_momoyo', ),
    HINANAWI_TENSHI: ('hinanawi_tenshi', ),
    HONG_MEILING: ('hong_meiling', ),
    HORIKAWA_RAIKO: ('horikawa_raiko', ),
    HOSHIGUMA_YUUGI: ('hoshiguma_yuugi', ),
    HOUJUU_NUE: ('houjuu_nue', ),
    HOURAISAN_KAGUYA: ('houraisan_kaguya', ),
    LILY_WHITE: ('lily_white', ),
    LETTY_WHITEROCK: ('letty_whiterock', ),
    IBARAKI_KASEN: ('ibaraki_kasen', ),
    IBUKI_SUIKA: ('ibuki_suika', ),
    IIZUNAMARU_MEGUMU: ('iizunamaru_megumu', ),
    IMAIZUMI_KAGEROU: ('imaizumi_kagerou', ),
    INABA_TEWI: ('inaba_tewi', ),
    INUBASHIRI_MOMIJI: ('inubashiri_momiji', ),
    IZAYOI_SAKUYA: ('izayoi_sakuya', ),
    JOUTOUGUU_MAYUMI: ('joutouguu_mayumi', ),
    JUNKO: ('junko_(touhou)', ),
    KAENBYOU_RIN: ('kaenbyou_rin', ),
    KAGIYAMA_HINA: ('kagiyama_hina', ),
    KAKU_SEIGA: ('kaku_seiga', ),
    KAMISHIRASAWA_KEINE: ('kamishirasawa_keine', ),
    KASODANI_KYOUKO: ('kasodani_kyouko', ),
    KAWASHIRO_NITORI: ('kawashiro_nitori', ),
    KAZAMI_YUUKA: ('kazami_yuuka', ),
    KICCHOU_YACHIE: ('kitcho_yachie', ),
    KIJIN_SEIJA: ('kijin_seija', ),
    KIRISAME_MARISA: ('kirisame_marisa', ),
    KISHIN_SAGUME: ('kishin_sagume', ),
    KISUME: ('kisume', ),
    KITASHIRAKAWA_CHIYURI: ('kitashirakawa_chiyuri', ),
    KOAKUMA: ('koakuma', ),
    KOCHIYA_SANAE: ('kochiya_sanae', ),
    KOMANO_AUNN: ('komano_aun', ),
    KOMEIJI_KOISHI: ('komeiji_koishi', ),
    KOMEIJI_SATORI: ('komeiji_satori', ),
    KONNGARA: ('konngara', ),
    KONPAKU_YOUMU: ('konpaku_youmu', ),
    KOKUU_HARUTO: ('kokuu_haruto', ),
    KUDAMAKI_TSUKASA: ('kudamaki_tsukasa', ),
    KUMOI_ICHIRIN: ('kumoi_ichirin', ),
    CLOWNPIECE: ('clownpiece', ),
    KURODANI_YAMAME: ('kurodani_yamame', ),
    KUROKOMA_SAKI: ('kurokoma_saki', ),
    MARGATROID_ALICE: ('alice_margatroid', ),
    MATARA_OKINA: ('matara_okina', ),
    MEDICINE_MELANCHOLY: ('medicine_melancholy', ),
    MIMA: ('mima', ),
    SUNNY_MILK: ('sunny_milk', ),
    MIYAKO_YOSHIKA: ('miyako_yoshika', ),
    MIZUHASHI_PARSEE: ('mizuhashi_parsee', ),
    MONONOBE_NO_FUTO: ('mononobe_no_futo', ),
    MORICHIKA_RINNOSUKE: ('morichika_rinnosuke', ),
    MORIYA_SUWAKO: ('moriya_suwako', ),
    MOTOORI_KOSUZU: ('motoori_kosuzu', ),
    MURASA_MINAMITSU: ('murasa_minamitsu', ),
    NAGAE_IKU: ('nagae_iku', ),
    NAZRIN: ('nazrin', ),
    NISHIDA_SATONO: ('nishida_satono', ),
    NIWATARI_KUTAKA: ('niwatari_kutaka', ),
    OKUNODA_MIYOI: ('okunoda_miyoi', ),
    ONOZUKA_KOMACHI: ('onozuka_komachi', ),
    PATCHOULI_KNOWLEDGE: ('patchouli_knowledge', ),
    MERLIN_PRISMRIVER: ('merlin_prismriver', ),
    LYRICA_PRISMRIVER: ('lyrica_prismriver', ),
    LUNASA_PRISMRIVER: ('lunasa_prismriver', ),
    HECATIA_LAPISLAZULI: ('hecatia_lapislazuli', ),
    REISEN_UDONGEIN_INABA: ('reisen_udongein_inaba', ),
    REIUJI_UTSUHO: ('reiuji_utsuho', ),
    WRIGGLE_NIGHTBUG: ('wriggle_nightbug', ),
    RINGO: ('ringo_(touhou)', ),
    MYSTIA_LORELEI: ('mystia_lorelei', ),
    RUMIA: ('rumia', ),
    STAR_SAPPHIRE: ('star_sapphire', ),
    SAIGYOUJI_YUYUKO: ('saigyouji_yuyuko', ),
    SAKATA_NEMUNO: ('sakata_nemuno', ),
    SEIRAN: ('seiran_(touhou)', ),
    SEKIBANKI: ('sekibanki', ),
    SHAMEIMARU_AYA: ('shameimaru_aya', ),
    SHIKI_EIKI_YAMAXANADU: ('shiki_eiki', ),
    DOREMY_SWEET: ('doremy_sweet', ),
    SCARLET_FLANDRE: ('flandre_scarlet', ),
    SCARLET_REMILIA: ('remilia_scarlet', ),
    SUKUNA_SHINMYOUMARU: ('sukuna_shinmyoumaru', ),
    TAMATSUKURI_MISUMARU: ('tamatsukuri_misumaru', ),
    TATARA_KOGASA: ('tatara_kogasa', ),
    TEIREIDA_MAI: ('teireida_mai', ),
    TENKYUU_CHIMATA: ('tenkyuu_chimata', ),
    TORAMARU_SHOU: ('toramaru_shou', ),
    TOUTETSU_YUUMA: ('toutetsu_yuuma', ),
    TOYOSATOMIMI_NO_MIKO: ('toyosatomimi_no_miko', ),
    USAMI_RENKO: ('usami_renko', ),
    USAMI_SUMIREKO: ('usami_sumireko', ),
    USHIZAKI_URUMI: ('ushizaki_urumi', ),
    WAKASAGIHIME: ('wakasagihime', ),
    WATATSUKI_NO_TOYOHIME: ('watatsuki_no_toyohime', ),
    WATATSUKI_NO_YORIHIME: ('watatsuki_no_yorihime', ),
    YAGOKORO_EIRIN: ('yagokoro_eirin', ),
    YAKUMO_RAN: ('yakumo_ran', ),
    YAKUMO_YUKARI: ('yakumo_yukari', ),
    YASAKA_KANAKO: ('yasaka_kanako', ),
    YATADERA_NARUMI: ('yatadera_narumi', ),
    YORIGAMI_JOON: ('yorigami_jo\'on', ),
    YORIGAMI_SHION: ('yorigami_shion', ),
}
