__all__ = (
    'ACTIONS', 'AUTO_CANCELLATIONS', 'DURATION_MAX', 'DURATION_MIN', 'DURATION_SUGGESTION_SETS', 'LOCATIONS',
    'RETURNS', 'TARGETS'
)

from collections import OrderedDict

from scarletio import WeakValueDictionary


AUTO_CANCELLATIONS = {}
ACTIONS = {}
DURATION_SUGGESTION_SETS = {}
LOCATIONS = {}
RETURNS = {}
TARGETS = {}


ADVENTURES = WeakValueDictionary()
ADVENTURE_CACHE = OrderedDict()
ADVENTURE_CACHE_SIZE_MAX = 100
ADVENTURE_QUERY_CACHE = {}
ADVENTURES_ACTIVE = {}

ADVENTURE_ACTION_LISTING_CACHE = OrderedDict()
ADVENTURE_ACTION_LISTING_CACHE_SIZE_MAX = 100
ADVENTURE_ACTION_LISTING_QUERY_CACHE = {}


DURATION_MIN = 14400
DURATION_MAX = 1209600
DISTANCE_DEFAULT = 1_000

RECOVERY_DURATION_BY_LOST_HEALTH = 960
RECOVERY_DURATION_BY_LOST_ENERGY = 120
RECOVERY_DURATION_MULTIPLIER_FATALITY = 5

ADVENTURE_LISTING_CACHE = OrderedDict()
ADVENTURE_LISTING_CACHE_SIZE_MAX = 100


TEST_MODE_DURATION_DIVIDER = 300
