__all__ = (
    'NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_DISABLE', 'NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_ENABLE',
    'NOTIFICATION_SETTINGS_CUSTOM_ID_PROPOSAL_DISABLE', 'NOTIFICATION_SETTINGS_CUSTOM_ID_PROPOSAL_ENABLE',
)


NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_ENABLE = 'notification_settings.daily.enable'
NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_DISABLE = 'notification_settings.daily.disable'

NOTIFICATION_SETTINGS_CUSTOM_ID_PROPOSAL_ENABLE = 'notification_settings.proposal.enable'
NOTIFICATION_SETTINGS_CUSTOM_ID_PROPOSAL_DISABLE = 'notification_settings.proposal.disable'
