__all__ = (
    'NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_BY_WAIFU_DISABLE', 'NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_BY_WAIFU_ENABLE',
    'NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_REMINDER_DISABLE', 'NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_REMINDER_ENABLE',
    'NOTIFICATION_SETTINGS_CUSTOM_ID_PROPOSAL_DISABLE', 'NOTIFICATION_SETTINGS_CUSTOM_ID_PROPOSAL_ENABLE',
)


NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_BY_WAIFU_ENABLE = 'notification_settings.daily_by_waifu.enable'
NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_BY_WAIFU_DISABLE = 'notification_settings.daily_by_waifu.disable'

NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_REMINDER_ENABLE = 'notification_settings.daily_reminder.enable'
NOTIFICATION_SETTINGS_CUSTOM_ID_DAILY_REMINDER_DISABLE = 'notification_settings.daily_reminder.disable'

NOTIFICATION_SETTINGS_CUSTOM_ID_PROPOSAL_ENABLE = 'notification_settings.proposal.enable'
NOTIFICATION_SETTINGS_CUSTOM_ID_PROPOSAL_DISABLE = 'notification_settings.proposal.disable'


NOTIFIER_NAME_DEFAULT = 'unset'
