__all__ = ('EMOJI_UNKNOWN', 'EMOJI_UNKNOWN_AS_EMOJI')

from hata import BUILTIN_EMOJIS


CHAPTER_STYLE_ID_DEFAULT = 0
CHAPTER_STYLE_ID_REIMU = 1
CHAPTER_STYLE_ID_FLANDRE = 2
CHAPTER_STYLE_ID_YUKARI = 3

EMOJI_UNKNOWN = BUILTIN_EMOJIS['flying_saucer']
EMOJI_UNKNOWN_AS_EMOJI = EMOJI_UNKNOWN.as_emoji
