__all__ = (
    'MODIFIER_ID__BUTCHERING', 'MODIFIER_ID__ENERGY', 'MODIFIER_ID__FISHING', 'MODIFIER_ID__FORAGING',
    'MODIFIER_ID__GARDENING', 'MODIFIER_ID__HEALTH', 'MODIFIER_ID__HUNTING', 'MODIFIER_ID__INVENTORY',
    'MODIFIER_ID__MOVEMENT', 'MODIFIER_ID__STAT_BEDROOM', 'MODIFIER_ID__STAT_CHARM', 'MODIFIER_ID__STAT_CUTENESS',
    'MODIFIER_ID__STAT_HOUSEWIFE', 'MODIFIER_ID__STAT_LOYALTY'
)

MODIFIER_ID__STAT_HOUSEWIFE = 1
MODIFIER_ID__STAT_CUTENESS = 2
MODIFIER_ID__STAT_BEDROOM = 3
MODIFIER_ID__STAT_CHARM = 4
MODIFIER_ID__STAT_LOYALTY = 5

MODIFIER_ID__INVENTORY = 6
MODIFIER_ID__MOVEMENT = 7
MODIFIER_ID__HEALTH = 8
MODIFIER_ID__ENERGY = 9

MODIFIER_ID__BUTCHERING = 10
MODIFIER_ID__FISHING = 11
MODIFIER_ID__GARDENING = 12
MODIFIER_ID__FORAGING = 13
MODIFIER_ID__HUNTING = 14


MODIFIER_ID_NAME_DEFAULT = 'Unknown'
MODIFIER_ID_NAMES = {
    MODIFIER_ID__STAT_HOUSEWIFE : 'Housewife capabilities',
    MODIFIER_ID__STAT_CUTENESS : 'Cuteness',
    MODIFIER_ID__STAT_BEDROOM : 'Bedroom skills',
    MODIFIER_ID__STAT_CHARM : 'Charm',
    MODIFIER_ID__STAT_LOYALTY : 'Loyalty',
    
    MODIFIER_ID__BUTCHERING : 'Butchering',
    MODIFIER_ID__FISHING : 'Fishing',
    MODIFIER_ID__FORAGING : 'Foraging',
    MODIFIER_ID__GARDENING : 'Gardening',
    MODIFIER_ID__HUNTING : 'Hunting',
    
    MODIFIER_ID__INVENTORY : 'Inventory capacity',
    MODIFIER_ID__MOVEMENT : 'Movement',
    MODIFIER_ID__HEALTH : 'Health',
    MODIFIER_ID__ENERGY : 'Energy',
}
