__all__ = ('MODIFIER_KIND__FLAT', 'MODIFIER_KIND__PERCENT')


MODIFIER_KIND__FLAT = 0
MODIFIER_KIND__PERCENT = 1

MODIFIER_KIND_MASK = 1
MODIFIER_KIND_SHIFT = 1

MODIFIER_KIND_POSTFIX_DEFAULT = '?'
MODIFIER_KIND_POSTFIXES = {
    MODIFIER_KIND__FLAT: None,
    MODIFIER_KIND__PERCENT: '%',
}
