__all__ = ()


from .constants import (
    BUTTON_SNIPE_ACTIONS_DISABLED, BUTTON_SNIPE_ACTIONS_EMOJI, BUTTON_SNIPE_ACTIONS_STICKER, BUTTON_SNIPE_ADD_DISABLED,
    BUTTON_SNIPE_ADD_EMOJI, BUTTON_SNIPE_ADD_STICKER, BUTTON_SNIPE_DETAILS_DISABLED, BUTTON_SNIPE_DM_DISABLED,
    BUTTON_SNIPE_EDIT_DISABLED, BUTTON_SNIPE_EDIT_EMOJI, BUTTON_SNIPE_EDIT_STICKER, BUTTON_SNIPE_REMOVE_DISABLED,
    BUTTON_SNIPE_REMOVE_EMOJI, BUTTON_SNIPE_REMOVE_STICKER, BUTTON_SNIPE_REVEAL_DISABLED, CUSTOM_ID_SNIPE_ACTIONS_EMOJI,
    CUSTOM_ID_SNIPE_ACTIONS_STICKER, CUSTOM_ID_SNIPE_ADD_DISABLED, CUSTOM_ID_SNIPE_ADD_EMOJI,
    CUSTOM_ID_SNIPE_ADD_STICKER, CUSTOM_ID_SNIPE_DETAILS_EMOJI, CUSTOM_ID_SNIPE_DETAILS_REACTION,
    CUSTOM_ID_SNIPE_DETAILS_STICKER, CUSTOM_ID_SNIPE_DM, CUSTOM_ID_SNIPE_EDIT_DISABLED, CUSTOM_ID_SNIPE_EDIT_EMOJI,
    CUSTOM_ID_SNIPE_EDIT_STICKER, CUSTOM_ID_SNIPE_REMOVE_DISABLED, CUSTOM_ID_SNIPE_REMOVE_EMOJI,
    CUSTOM_ID_SNIPE_REMOVE_STICKER, CUSTOM_ID_SNIPE_REVEAL
)


SELECT_EMOJI_OUTSIDE = {
    # emoji
    CUSTOM_ID_SNIPE_ADD_DISABLED: BUTTON_SNIPE_ADD_EMOJI,
    CUSTOM_ID_SNIPE_EDIT_EMOJI: BUTTON_SNIPE_EDIT_DISABLED,
    CUSTOM_ID_SNIPE_REMOVE_EMOJI: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_ACTIONS_EMOJI: BUTTON_SNIPE_ACTIONS_EMOJI,
    
    # stickers
    CUSTOM_ID_SNIPE_ADD_STICKER: BUTTON_SNIPE_ADD_EMOJI,
    CUSTOM_ID_SNIPE_EDIT_STICKER: BUTTON_SNIPE_EDIT_DISABLED,
    CUSTOM_ID_SNIPE_REMOVE_STICKER: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_ACTIONS_STICKER: BUTTON_SNIPE_ACTIONS_EMOJI,
}

SELECT_EMOJI_INSIDE = {
    # emoji
    CUSTOM_ID_SNIPE_ADD_EMOJI: BUTTON_SNIPE_ADD_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_DISABLED: BUTTON_SNIPE_EDIT_EMOJI,
    CUSTOM_ID_SNIPE_REMOVE_DISABLED: BUTTON_SNIPE_REMOVE_EMOJI,
    CUSTOM_ID_SNIPE_ACTIONS_EMOJI: BUTTON_SNIPE_ACTIONS_EMOJI,
    
    # stickers
    CUSTOM_ID_SNIPE_ADD_STICKER: BUTTON_SNIPE_ADD_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_STICKER: BUTTON_SNIPE_EDIT_EMOJI,
    CUSTOM_ID_SNIPE_REMOVE_STICKER: BUTTON_SNIPE_REMOVE_EMOJI,
    CUSTOM_ID_SNIPE_ACTIONS_STICKER: BUTTON_SNIPE_ACTIONS_EMOJI,
}

SELECT_EMOJI_DISABLED = {
    # emoji
    CUSTOM_ID_SNIPE_ADD_EMOJI: BUTTON_SNIPE_ADD_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_EMOJI: BUTTON_SNIPE_EDIT_DISABLED,
    CUSTOM_ID_SNIPE_REMOVE_EMOJI: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_ACTIONS_EMOJI: BUTTON_SNIPE_ACTIONS_EMOJI,
    
    # sticker
    CUSTOM_ID_SNIPE_ADD_STICKER: BUTTON_SNIPE_ADD_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_STICKER: BUTTON_SNIPE_EDIT_DISABLED,
    CUSTOM_ID_SNIPE_REMOVE_STICKER: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_ACTIONS_STICKER: BUTTON_SNIPE_ACTIONS_EMOJI,
}

SELECT_STICKER_OUTSIDE = {
    # emoji
    CUSTOM_ID_SNIPE_ADD_EMOJI: BUTTON_SNIPE_ADD_STICKER,
    CUSTOM_ID_SNIPE_EDIT_EMOJI: BUTTON_SNIPE_EDIT_DISABLED,
    CUSTOM_ID_SNIPE_REMOVE_EMOJI: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_ACTIONS_EMOJI: BUTTON_SNIPE_ACTIONS_STICKER,
    
    # stickers
    CUSTOM_ID_SNIPE_ADD_DISABLED: BUTTON_SNIPE_ADD_STICKER,
    CUSTOM_ID_SNIPE_EDIT_STICKER: BUTTON_SNIPE_EDIT_DISABLED,
    CUSTOM_ID_SNIPE_REMOVE_STICKER: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_ACTIONS_STICKER: BUTTON_SNIPE_ACTIONS_STICKER,
}

SELECT_STICKER_INSIDE = {
    # emoji
    CUSTOM_ID_SNIPE_ADD_EMOJI: BUTTON_SNIPE_ADD_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_EMOJI: BUTTON_SNIPE_EDIT_STICKER,
    CUSTOM_ID_SNIPE_REMOVE_EMOJI: BUTTON_SNIPE_REMOVE_STICKER,
    CUSTOM_ID_SNIPE_ACTIONS_EMOJI: BUTTON_SNIPE_ACTIONS_STICKER,
    
    # stickers
    CUSTOM_ID_SNIPE_ADD_STICKER: BUTTON_SNIPE_ADD_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_DISABLED: BUTTON_SNIPE_EDIT_STICKER,
    CUSTOM_ID_SNIPE_REMOVE_DISABLED: BUTTON_SNIPE_REMOVE_STICKER,
    CUSTOM_ID_SNIPE_ACTIONS_STICKER: BUTTON_SNIPE_ACTIONS_STICKER,
}

SELECT_STICKER_DISABLED = {
    # emoji
    CUSTOM_ID_SNIPE_ADD_EMOJI: BUTTON_SNIPE_ADD_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_EMOJI: BUTTON_SNIPE_EDIT_DISABLED,
    CUSTOM_ID_SNIPE_REMOVE_EMOJI: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_ACTIONS_EMOJI: BUTTON_SNIPE_ACTIONS_STICKER,
    
    # sticker
    CUSTOM_ID_SNIPE_ADD_STICKER: BUTTON_SNIPE_ADD_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_STICKER: BUTTON_SNIPE_EDIT_DISABLED,
    CUSTOM_ID_SNIPE_REMOVE_STICKER: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_ACTIONS_STICKER: BUTTON_SNIPE_ACTIONS_STICKER,
}


REVEAL_DISABLE = {
    CUSTOM_ID_SNIPE_REVEAL: BUTTON_SNIPE_REVEAL_DISABLED,
}


REMOVE_DISABLE = {
    CUSTOM_ID_SNIPE_REMOVE_EMOJI: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_REMOVE_STICKER: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_EMOJI: BUTTON_SNIPE_EDIT_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_STICKER: BUTTON_SNIPE_EDIT_DISABLED,
}

DM_DISABLE = {
    CUSTOM_ID_SNIPE_REVEAL: BUTTON_SNIPE_REVEAL_DISABLED,
    CUSTOM_ID_SNIPE_DM: BUTTON_SNIPE_DM_DISABLED,
    CUSTOM_ID_SNIPE_ACTIONS_EMOJI: BUTTON_SNIPE_ACTIONS_DISABLED,
    CUSTOM_ID_SNIPE_ACTIONS_STICKER: BUTTON_SNIPE_ACTIONS_DISABLED,
    CUSTOM_ID_SNIPE_ADD_EMOJI: BUTTON_SNIPE_ADD_DISABLED,
    CUSTOM_ID_SNIPE_ADD_STICKER: BUTTON_SNIPE_ADD_DISABLED,
    CUSTOM_ID_SNIPE_REMOVE_EMOJI: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_REMOVE_STICKER: BUTTON_SNIPE_REMOVE_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_EMOJI: BUTTON_SNIPE_EDIT_DISABLED,
    CUSTOM_ID_SNIPE_EDIT_STICKER: BUTTON_SNIPE_EDIT_DISABLED,
}

DETAILS_DISABLE = {
    CUSTOM_ID_SNIPE_DETAILS_EMOJI: BUTTON_SNIPE_DETAILS_DISABLED,
    CUSTOM_ID_SNIPE_DETAILS_REACTION: BUTTON_SNIPE_DETAILS_DISABLED,
    CUSTOM_ID_SNIPE_DETAILS_STICKER: BUTTON_SNIPE_DETAILS_DISABLED,
}


ADD_DISABLE = {
    CUSTOM_ID_SNIPE_ADD_EMOJI: BUTTON_SNIPE_ADD_DISABLED,
    CUSTOM_ID_SNIPE_ADD_STICKER: BUTTON_SNIPE_ADD_DISABLED,
}

ACTIONS_DISABLE = {
    CUSTOM_ID_SNIPE_ACTIONS_EMOJI: BUTTON_SNIPE_ACTIONS_DISABLED,
    CUSTOM_ID_SNIPE_ACTIONS_STICKER: BUTTON_SNIPE_ACTIONS_DISABLED,
}
