__all__ = ('GUILD_INFO_FIELD_DEFAULT', 'GUILD_INFO_FIELDS')

GUILD_INFO_SELECT_CUSTOM_ID = 'guild.info.select'

GUILD_INFO_FIELD_DEFAULT = 'info'
GUILD_INFO_FIELD_COUNTS = 'counts'
GUILD_INFO_FIELD_EMOJIS = 'emojis'
GUILD_INFO_FIELD_STICKERS = 'sticker'
GUILD_INFO_FIELD_BOOSTERS = 'boosters'
GUILD_INFO_FIELD_ALL = 'all'


GUILD_INFO_FIELDS = [
    GUILD_INFO_FIELD_DEFAULT,
    GUILD_INFO_FIELD_COUNTS,
    GUILD_INFO_FIELD_EMOJIS,
    GUILD_INFO_FIELD_STICKERS,
    GUILD_INFO_FIELD_BOOSTERS,
    GUILD_INFO_FIELD_ALL,
]
