__all__ = ()

GUILD_INFO_SELECT_CUSTOM_ID = 'guild.info.select'

GUILD_INFO_FLAG_EVEN_IF_EMPTY = 1 << 0

GUILD_INFO_FLAG_INFO = 1 << 1
GUILD_INFO_FLAG_COUNTS = 1 << 2
GUILD_INFO_FLAG_EMOJIS = 1 << 3
GUILD_INFO_FLAG_STICKERS = 1 << 4
GUILD_INFO_FLAG_BOOST_PERKS = 1 << 5
GUILD_INFO_FLAG_BOOSTERS = 1 << 6


GUILD_INFO_FLAGS = [
    ('info', GUILD_INFO_FLAG_INFO | GUILD_INFO_FLAG_EVEN_IF_EMPTY),
    ('counts', GUILD_INFO_FLAG_COUNTS | GUILD_INFO_FLAG_EVEN_IF_EMPTY),
    ('emojis', GUILD_INFO_FLAG_EMOJIS | GUILD_INFO_FLAG_EVEN_IF_EMPTY),
    ('stickers', GUILD_INFO_FLAG_STICKERS | GUILD_INFO_FLAG_EVEN_IF_EMPTY),
    ('boost perks', GUILD_INFO_FLAG_BOOST_PERKS | GUILD_INFO_FLAG_EVEN_IF_EMPTY),
    ('boosters', GUILD_INFO_FLAG_BOOSTERS | GUILD_INFO_FLAG_EVEN_IF_EMPTY),
    (
        'all',
        GUILD_INFO_FLAG_INFO | GUILD_INFO_FLAG_COUNTS | GUILD_INFO_FLAG_EMOJIS | GUILD_INFO_FLAG_STICKERS |
        GUILD_INFO_FLAG_BOOST_PERKS | GUILD_INFO_FLAG_BOOSTERS
    ),
]
