__all__ = ()

from ...item_core import (
    ITEM_ID_BLUEFRANKISH, ITEM_ID_BISHOPHAT, ITEM_ID_ANGELROOT, ITEM_ID_CARROT, ITEM_ID_DEVILCART_OYSTER,
    ITEM_ID_FISHING_ROD, ITEM_ID_FLYKILLER_AMANITA, ITEM_ID_FROG, ITEM_ID_GARLIC, ITEM_ID_SCARLET_ONION,
    ITEM_ID_SCISSORS, ITEM_ID_STRAWBERRY, ITEM_ID_PEACH, ITEM_ID_BLUEBERRY
)

from ..constants import ACTIONS
from ..options import OptionLoot

from .action import Action
from .action_ids import (
    ACTION_ID_BAMBOO_FOREST_FORAGING_CATEGORY_MUSHROOM, ACTION_ID_BAMBOO_FOREST_TRAP_RABBIT,
    ACTION_ID_EIENTEI_MANSION_GARDENING_CARROT, ACTION_ID_EIENTEI_MANSION_TRAP_RABBIT,
    ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_CARROT, ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_GARLIC,
    ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_SCARLET_ONION, ACTION_ID_HUMAN_VILLAGE_VINEYARDS_GARDENING_BLUEFRANKISH,
    ACTION_ID_RUINS_FORAGING_STRAWBERRY, ACTION_ID_SYSTEM_ARRIVAL, ACTION_ID_SYSTEM_CANCELLATION,
    ACTION_ID_SYSTEM_FATALITY, ACTION_ID_SYSTEM_UNKNOWN, ACTION_ID_MISTY_LAKE_FORAGING,
    ACTION_ID_MORIYA_SHRINE_FORAGING_BLUEBERRY, ACTION_ID_HAKUGYOKUROU_MANSION_GARDENING_PEACH
)
from .action_types import (
    ACTION_TYPE_ARRIVAL, ACTION_TYPE_CANCELLATION, ACTION_TYPE_FATALITY, ACTION_TYPE_FORAGING, ACTION_TYPE_GARDENING,
    ACTION_TYPE_TRAP, ACTION_TYPE_UNKNOWN
)


ACTION_SYSTEM_CANCELLATION = \
ACTIONS[ACTION_ID_SYSTEM_CANCELLATION] = Action(
    ACTION_ID_SYSTEM_CANCELLATION,
    ACTION_TYPE_CANCELLATION,
    0,
    0,
    None,
    None,
)


ACTION_SYSTEM_ARRIVAL = \
ACTIONS[ACTION_ID_SYSTEM_ARRIVAL] = Action(
    ACTION_ID_SYSTEM_ARRIVAL,
    ACTION_TYPE_ARRIVAL,
    0,
    0,
    None,
    None,
)


ACTION_SYSTEM_FATALITY = \
ACTIONS[ACTION_ID_SYSTEM_FATALITY] = Action(
    ACTION_ID_SYSTEM_FATALITY,
    ACTION_TYPE_FATALITY,
    0,
    0,
    None,
    None,
)


ACTION_SYSTEM_UNKNOWN = \
ACTIONS[ACTION_ID_SYSTEM_UNKNOWN] = Action(
    ACTION_ID_SYSTEM_UNKNOWN,
    ACTION_TYPE_UNKNOWN,
    0,
    0,
    None,
    None,
)


ACTION_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_SCARLET_ONION = \
ACTIONS[ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_SCARLET_ONION] = Action(
    ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_SCARLET_ONION,
    ACTION_TYPE_GARDENING,
    3600,
    1,
    None,
    (
        OptionLoot(1, 1, 5, 20, ITEM_ID_SCARLET_ONION, 300, 40, 10, 2),
        OptionLoot(1, 100, 50, 75, ITEM_ID_SCARLET_ONION, 0, 20, 0, 1),
        OptionLoot(1, 230, 1, 1, ITEM_ID_FROG, 0, 120, 0, 1),
    ),
)


ACTION__HUMAN_VILLAGE_VINEYARDS_GARDENING_BLUEFRANKISH = \
ACTIONS[ACTION_ID_HUMAN_VILLAGE_VINEYARDS_GARDENING_BLUEFRANKISH] = Action(
    ACTION_ID_HUMAN_VILLAGE_VINEYARDS_GARDENING_BLUEFRANKISH,
    ACTION_TYPE_GARDENING,
    1600,
    1,
    None,
    (
        OptionLoot(1, 1, 10, 20, ITEM_ID_BLUEFRANKISH, 2400, 20, 10, 1),
        OptionLoot(1, 100, 10, 40, ITEM_ID_BLUEFRANKISH, 300, 10, 10, 1),
    ),
)


ACTION_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_CARROT = \
ACTIONS[ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_CARROT] = Action(
    ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_CARROT,
    ACTION_TYPE_GARDENING,
    3000,
    1,
    None,
    (
        OptionLoot(1, 1, 5, 10, ITEM_ID_CARROT, 100, 60, 10, 2),
        OptionLoot(1, 100, 25, 40, ITEM_ID_CARROT, 0, 60, 0, 2),
        OptionLoot(1, 230, 1, 1, ITEM_ID_FROG, 0, 120, 0, 1),
    ),
)


ACTION_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_GARLIC = \
ACTIONS[ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_GARLIC] = Action(
    ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_GARLIC,
    ACTION_TYPE_GARDENING,
    3600,
    1,
    None,
    (
        OptionLoot(1, 1, 5, 10, ITEM_ID_GARLIC, 100, 50, 10, 1),
        OptionLoot(1, 100, 25, 30, ITEM_ID_GARLIC, 0, 25, 0, 1),
        OptionLoot(1, 230, 1, 1, ITEM_ID_FROG, 0, 120, 0, 1),
    ),
)


ACTION_HUMAN_RUIN_FORAGING_STRAWBERRY = \
ACTIONS[ACTION_ID_RUINS_FORAGING_STRAWBERRY] = Action(
    ACTION_ID_RUINS_FORAGING_STRAWBERRY,
    ACTION_TYPE_FORAGING,
    1800,
    1,
    None,
    (
        OptionLoot(3, 4, 5, 25, ITEM_ID_STRAWBERRY, 600, 15, 1, 1),
        OptionLoot(1, 80, 1, 4, ITEM_ID_BISHOPHAT, 100, 300, 1, 5),
    ),
)


ACTION_EIENTEI_MANSION_TRAP_RABBIT = \
ACTIONS[ACTION_ID_EIENTEI_MANSION_TRAP_RABBIT] = Action(
    ACTION_ID_EIENTEI_MANSION_TRAP_RABBIT,
    ACTION_TYPE_TRAP,
    5400,
    1,
    None,
    None,
)


ACTION_EIENTEI_MANSION_GARDENING_CARROT = \
ACTIONS[ACTION_ID_EIENTEI_MANSION_GARDENING_CARROT] = Action(
    ACTION_ID_EIENTEI_MANSION_GARDENING_CARROT,
    ACTION_TYPE_GARDENING,
    3600,
    19,
    None,
    (
        OptionLoot(1, 1, 10, 15, ITEM_ID_CARROT, 0, 90, 15, 2),
        OptionLoot(1, 230, 1, 1, ITEM_ID_FROG, 0, 120, 0, 1),
    ),
)


ACTION_BAMBOO_FOREST_TRAP_RABBIT = \
ACTIONS[ACTION_ID_BAMBOO_FOREST_TRAP_RABBIT] = Action(
    ACTION_ID_BAMBOO_FOREST_TRAP_RABBIT,
    ACTION_TYPE_TRAP,
    7200,
    1,
    None,
    None,
)


ACTION_BAMBOO_FOREST_FORAGING_CATEGORY_MUSHROOM = \
ACTIONS[ACTION_ID_BAMBOO_FOREST_FORAGING_CATEGORY_MUSHROOM] = Action(
    ACTION_ID_BAMBOO_FOREST_FORAGING_CATEGORY_MUSHROOM,
    ACTION_TYPE_FORAGING,
    4200,
    19,
    None,
    (
        OptionLoot(4, 5, 2, 7, ITEM_ID_DEVILCART_OYSTER, 120, 10, 2, 1),
        OptionLoot(1, 10, 1, 4, ITEM_ID_FLYKILLER_AMANITA, 600, 10, 6, 3),
        OptionLoot(1, 40, 1, 3, ITEM_ID_BISHOPHAT, 200, 300, 1, 5),
        OptionLoot(1, 800, 1, 1, ITEM_ID_SCISSORS, 300, 0, 1, 0),
    ),
)


ACTION_HUMAN_VILLAGE_OUTSKIRTS_FORAGING_BLUEBERRY = \
ACTIONS[ACTION_ID_MORIYA_SHRINE_FORAGING_BLUEBERRY] = Action(
    ACTION_ID_MORIYA_SHRINE_FORAGING_BLUEBERRY,
    ACTION_TYPE_FORAGING,
    1800,
    1,
    None,
    (
        OptionLoot(3, 4, 4, 20, ITEM_ID_BLUEBERRY, 600, 15, 1, 1),
    ),
)


ACTION_HAKUGYOKUROU_MANSION_GARDENING_PEACH = \
ACTIONS[ACTION_ID_HAKUGYOKUROU_MANSION_GARDENING_PEACH] = Action(
    ACTION_ID_HAKUGYOKUROU_MANSION_GARDENING_PEACH,
    ACTION_TYPE_GARDENING,
    2700,
    1,
    None,
    (
        OptionLoot(1, 2, 8, 22, ITEM_ID_PEACH, 200, 40, 6, 1),
        OptionLoot(1, 200, 20, 34, ITEM_ID_PEACH, 0, 20, 0, 1),
    ),
)


ACTION_MISTY_LAKE_FORAGING = \
ACTIONS[ACTION_ID_MISTY_LAKE_FORAGING] = Action(
    ACTION_ID_MISTY_LAKE_FORAGING,
    ACTION_TYPE_FORAGING,
    3600,
    1,
    None,
    (
        OptionLoot(3, 5, 1, 4, ITEM_ID_FROG, 60, 300, 1, 2),
        OptionLoot(2, 5, 1, 4, ITEM_ID_ANGELROOT, 100, 200, 2, 3),
        OptionLoot(1, 200, 1, 1, ITEM_ID_FISHING_ROD, 300, 10, 1, 0),
    ),
)
