__all__ = (
    'ACTION_TYPE_ARRIVAL', 'ACTION_TYPE_BUTCHERING', 'ACTION_TYPE_CANCELLATION', 'ACTION_TYPE_ENCOUNTER',
    'ACTION_TYPE_FATALITY', 'ACTION_TYPE_FISHING', 'ACTION_TYPE_FORAGING', 'ACTION_TYPE_GARDENING', 'ACTION_TYPE_HUNT',
    'ACTION_TYPE_NONE', 'ACTION_TYPE_TRAP', 'ACTION_TYPE_UNKNOWN'
)


ACTION_TYPE_NONE = 0
ACTION_TYPE_CANCELLATION = 1
ACTION_TYPE_ARRIVAL = 2
ACTION_TYPE_FATALITY = 3
ACTION_TYPE_UNKNOWN = 4

ACTION_TYPE_GARDENING = 100
ACTION_TYPE_FORAGING = 101
ACTION_TYPE_BUTCHERING = 102

ACTION_TYPE_FISHING = 200
ACTION_TYPE_ENCOUNTER = 201
ACTION_TYPE_HUNT = 202

ACTION_TYPE_TRAP = 300
