__all__ = (
    'ACTION_ID_BAMBOO_FOREST_FORAGING_CATEGORY_MUSHROOM', 'ACTION_ID_BAMBOO_FOREST_TRAP_RABBIT',
    
    'ACTION_ID_EIENTEI_MANSION_GARDENING_CARROT', 'ACTION_ID_EIENTEI_MANSION_TRAP_RABBIT',
    
    'ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_CARROT', 'ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_GARLIC',
    'ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_SCARLET_ONION',
    
    'ACTION_ID_HUMAN_VILLAGE_VINEYARDS_GARDENING_BLUEFRANKISH',
    
    'ACTION_ID_RUINS_FORAGING_STRAWBERRY',
    
    'ACTION_ID_SYSTEM_ARRIVAL', 'ACTION_ID_SYSTEM_CANCELLATION', 'ACTION_ID_SYSTEM_FATALITY', 'ACTION_ID_SYSTEM_UNKNOWN',
)


ACTION_ID_SYSTEM_CANCELLATION = 1
ACTION_ID_SYSTEM_ARRIVAL = 2
ACTION_ID_SYSTEM_FATALITY = 3
ACTION_ID_SYSTEM_UNKNOWN = 4

ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_SCARLET_ONION = 100
ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_CARROT = 101
ACTION_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_GARLIC = 102


ACTION_ID_HUMAN_VILLAGE_VINEYARDS_GARDENING_BLUEFRANKISH = 200


ACTION_ID_RUINS_FORAGING_STRAWBERRY = 204


ACTION_ID_EIENTEI_MANSION_TRAP_RABBIT = 300
ACTION_ID_EIENTEI_MANSION_GARDENING_CARROT = 301

ACTION_ID_BAMBOO_FOREST_TRAP_RABBIT = 400
ACTION_ID_BAMBOO_FOREST_FORAGING_CATEGORY_MUSHROOM = 401
