__all__ = ('TOUHOU_SAFE_BOORU_TAGS',)

from .characters import (
    AKI_MINORIKO, AKI_SHIZUHA, AKIYO, ANABERAL_KANA, ASAKURA_RIKAKO, AYANA, CHEN, CHIRIZUKA_UBAME, CHIRUNO, CLOWNPIECE,
    DAIYOUSEI, DOREMY_SWEET, EBISU_EIKA, ELIS, ELLEN, ELLY, ETERNITY_LARVA, FUJIWARA_NO_MOKOU, FUTATSUIWA_MAMIZOU,
    GENGETSU, GENJII, GOLIATH, HAKUREI_MIKO, HAKUREI_REIMU, HARURU, HANIYASUSHIN_KEIKI, HATA_NO_KOKORO, HEARN_MARIBEL,
    HECATIA_LAPISLAZULI, HEI_MEILING, HIEDA_NO_AKYUU, HIJIRI_BYAKUREN, HIMEKAIDOU_HATATE, HIMEMUSHI_MOMOYO,
    HINANAWI_TENSHI, HONG_MEILING, HORIKAWA_RAIKO, HOSHIGUMA_YUUGI, HOUJUU_CHIMI, HOUJUU_NUE, HOURAI, HOURAISAN_KAGUYA,
    IBARAKI_KASEN, IBUKI_SUIKA, IIZUNAMARU_MEGUMU, IMAIZUMI_KAGEROU, INABA_TEWI, INUBASHIRI_MOMIJI, IZAYOI_SAKUYA,
    JACKET, JOUTOUGUU_MAYUMI, JUNKO, KAENBYOU_RIN, KAGIYAMA_HINA, KAKU_SEIGA, KAMISHIRASAWA_KEINE, KASODANI_KYOUKO,
    KAWASHIRO_NITORI, KAZAMI_YUUKA, KICCHOU_YACHIE, KIJIN_SEIJA, KIKURI, KIRISAME_MARISA, KISHIN_SAGUME, KISUME,
    KITASHIRAKAWA_CHIYURI, KOAKUMA, KOCHIYA_SANAE, KOKUU_HARUTO, KOMAKUSA_SANNYO, KOMANO_AUNN, KOMEIJI_KOISHI,
    KOMEIJI_SATORI, KONNGARA, KONPAKU_YOUKI, KONPAKU_YOUMU, KOTOHIME, KUDAMAKI_TSUKASA, KUMOI_ICHIRIN, KURODANI_YAMAME,
    KUROKOMA_SAKI, KURUMI, LABEL, LETTY_WHITEROCK, LILY_BLACK, LILY_WHITE, LOUISE, LUNA_CHILD, MAI, MARGATROID_ALICE,
    MATARA_OKINA, MATENSHI, MEDICINE_MELANCHOLY, MEIRA, MICHIGAMI_NAREKO, MIMA, MISHAGUJI, MITSUGASHIRA_ENOKO,
    MIYADEGUCHI_MIZUCHI, MIYAKO_YOSHIKA, MIZUHASHI_PARSEE, MONONOBE_NO_FUTO, MORICHIKA_RINNOSUKE, MORIYA_SUWAKO,
    MOTOORI_KOSUZU, MUGETSU, MURASA_MINAMITSU, LORELEI_MYSTIA, NAGAE_IKU, NAZRIN, NIPPAKU_ZANMU, NISHIDA_SATONO,
    NIWATARI_KUTAKA, NOROIKO, OKAZAKI_YUMEMI, OKUNODA_MIYOI, ONOZUKA_KOMACHI, ORANGE, PATCHOULI_KNOWLEDGE,
    PRISMRIVER_LAYLA, PRISMRIVER_LUNASA, PRISMRIVER_LYRICA, PRISMRIVER_MERLIN, REISEN_UDONGEIN_INABA, REIUJI_UTSUHO,
    RENGETEKI, RIKA, RINGO, RUMIA, RUUKOTO, SAIGYOUJI_YUYUKO, SAKATA_NEMUNO, SARA, SARIEL, SATOWA, SATSUKI_RIN,
    SCARLET_FLANDRE, SCARLET_REMILIA, SEIRAN, SEKIBANKI, SHAMEIMARU_AYA, SHANGHAI, SHIKI_EIKI_YAMAXANADU, SHINGYOKU,
    SHINKI, SOGA_NO_TOJIKO, SOKRATES, SON_BITEN, STAR_SAPPHIRE, SUKUNA_SHINMYOUMARU, SUNNY_MILK, TAMATSUKURI_MISUMARU,
    TATARA_KOGASA, TEIREIDA_MAI, TENKAJIN_CHIYARI, TENKYUU_CHIMATA, TOKIKO, TOMOMI, TORAMARU_SHOU, TOUTETSU_YUUMA,
    TOYOSATOMIMI_NO_MIKO, TSUBAME, TSUKUMO_BENBEN, TSUKUMO_YATSUHASHI, UNNAMED_EXOTIC_GIRL_20000_HIT_GIRL,
    UNNAMED_EXOTIC_GIRL_CLEANING_MAID, USAMI_RENKO, USAMI_SUMIREKO, USHIZAKI_URUMI, VIVIT, WAKASAGIHIME,
    WATATSUKI_NO_TOYOHIME, WATATSUKI_NO_YORIHIME, WAYOUSEI, WRIGGLE_NIGHTBUG, YAGOKORO_EIRIN, YAKUMO_RAN,
    YAKUMO_YUKARI, YAMASHIRO_TAKANE, YASAKA_KANAKO, YATADERA_NARUMI, YOMOTSU_HISAMI, YORIGAMI_JOON, YORIGAMI_SHION,
    YORUMI, YUKI, YUMEKO, YUUGEN_MAGAN
)

TOUHOU_SAFE_BOORU_TAGS = {
    AKI_MINORIKO: ('aki_minoriko', ),
    AKI_SHIZUHA: ('aki_shizuha', ),
    AKIYO: ('blonde_shrine_maiden_from_a_future_era_(touhou)', ),
    ANABERAL_KANA: ('kana_anaberal', ),
    ASAKURA_RIKAKO: ('asakura_rikako', ),
    AYANA: ('ayana_(touhou)', ),
    CHEN: ('chen', ),
    CHIRIZUKA_UBAME: ('chirizuka_ubame', ),
    CHIRUNO: ('cirno', ),
    DAIYOUSEI: ('daiyousei', ),
    DOREMY_SWEET: ('doremy_sweet', ),
    EBISU_EIKA: ('ebisu_eika', ),
    ELIS: ('elis_(touhou)', ),
    ELLEN: ('ellen', 'ellen_(touhou)'),
    ELLY: ('elly', 'elly_(touhou)'),
    ETERNITY_LARVA: ('eternity_larva', ),
    FUJIWARA_NO_MOKOU: ('fujiwara_no_mokou', ),
    FUTATSUIWA_MAMIZOU: ('futatsuiwa_mamizou', ),
    GENGETSU: ('gengetsu_(touhou)', ),
    GENJII: ('genjii_(touhou)', ),
    GOLIATH: ('goliath_doll', ),
    HEARN_MARIBEL: ('maribel_hearn', ),
    HANIYASUSHIN_KEIKI: ('haniyasushin_keiki', ),
    HAKUREI_MIKO: ('sendai_hakurei_no_miko',),
    HAKUREI_REIMU: ('hakurei_reimu', ),
    HARURU: ('blonde_oekaki_girl_(touhou)', ),
    HATA_NO_KOKORO: ('hata_no_kokoro', ),
    HEI_MEILING: ('hei_meiling', ),
    HIEDA_NO_AKYUU: ('hieda_no_akyuu', ),
    HIJIRI_BYAKUREN: ('hijiri_byakuren', ),
    HIMEKAIDOU_HATATE: ('himekaidou_hatate', ),
    HIMEMUSHI_MOMOYO: ('himemushi_momoyo', ),
    HINANAWI_TENSHI: ('hinanawi_tenshi', ),
    HONG_MEILING: ('hong_meiling', ),
    HORIKAWA_RAIKO: ('horikawa_raiko', ),
    HOSHIGUMA_YUUGI: ('hoshiguma_yuugi', ),
    HOUJUU_NUE: ('houjuu_nue', ),
    HOUJUU_CHIMI: ('houjuu_chimi', ),
    HOURAI: ('hourai_doll', ),
    HOURAISAN_KAGUYA: ('houraisan_kaguya', ),
    LABEL: ('label_girl_(dipp)', ),
    LILY_BLACK: ('lily_black', ),
    LILY_WHITE: ('lily_white', ),
    LETTY_WHITEROCK: ('letty_whiterock', ),
    LOUISE: ('louise_(touhou)', ),
    LUNA_CHILD: ('luna_child', ),
    IBARAKI_KASEN: ('ibaraki_kasen', ),
    IBUKI_SUIKA: ('ibuki_suika', ),
    IIZUNAMARU_MEGUMU: ('iizunamaru_megumu', ),
    IMAIZUMI_KAGEROU: ('imaizumi_kagerou', ),
    INABA_TEWI: ('inaba_tewi', ),
    INUBASHIRI_MOMIJI: ('inubashiri_momiji', ),
    IZAYOI_SAKUYA: ('izayoi_sakuya', ),
    JACKET: ('jacket_girl_(dipp)', ),
    JOUTOUGUU_MAYUMI: ('joutouguu_mayumi', ),
    JUNKO: ('junko_(touhou)', ),
    KAENBYOU_RIN: ('kaenbyou_rin', ),
    KAGIYAMA_HINA: ('kagiyama_hina', ),
    KAKU_SEIGA: ('kaku_seiga', ),
    KAMISHIRASAWA_KEINE: ('kamishirasawa_keine', ),
    KASODANI_KYOUKO: ('kasodani_kyouko', ),
    KAWASHIRO_NITORI: ('kawashiro_nitori', ),
    KAZAMI_YUUKA: ('kazami_yuuka', ),
    KICCHOU_YACHIE: ('kitcho_yachie', ),
    KIKURI: ('kikuri_(touhou)', ),
    KIJIN_SEIJA: ('kijin_seija', ),
    KIRISAME_MARISA: ('kirisame_marisa', ),
    KISHIN_SAGUME: ('kishin_sagume', ),
    KISUME: ('kisume', ),
    KITASHIRAKAWA_CHIYURI: ('kitashirakawa_chiyuri', ),
    KOAKUMA: ('koakuma', ),
    KOCHIYA_SANAE: ('kochiya_sanae', ),
    KOKUU_HARUTO: ('kokuu_haruto', ),
    KOTOHIME: ('kotohime', 'kotohime_(touhou)'),
    KOMANO_AUNN: ('komano_aun', ),
    KOMAKUSA_SANNYO: ('komakusa_sannyo', ),
    KOMEIJI_KOISHI: ('komeiji_koishi', ),
    KOMEIJI_SATORI: ('komeiji_satori', ),
    KONNGARA: ('konngara', ),
    KONPAKU_YOUKI: ('konpaku_youki', ),
    KONPAKU_YOUMU: ('konpaku_youmu', ),
    KUDAMAKI_TSUKASA: ('kudamaki_tsukasa', ),
    KUMOI_ICHIRIN: ('kumoi_ichirin', ),
    KURUMI: ('kurumi_(touhou)', ),
    CLOWNPIECE: ('clownpiece', ),
    KURODANI_YAMAME: ('kurodani_yamame', ),
    KUROKOMA_SAKI: ('kurokoma_saki', ),
    MAI: ('mai_(touhou)', ),
    MARGATROID_ALICE: ('alice_margatroid', ),
    MATARA_OKINA: ('matara_okina', ),
    MATENSHI: ('matenshi_(touhou) ', ),
    MEDICINE_MELANCHOLY: ('medicine_melancholy', ),
    MEIRA: ('meira_(touhou)', ),
    MICHIGAMI_NAREKO: ('michigami_nareko', ),
    MIMA: ('mima', ),
    SUNNY_MILK: ('sunny_milk', ),
    MISHAGUJI: ('mishaguji', ),
    MITSUGASHIRA_ENOKO: ('mitsugashira_enoko', ),
    MIYADEGUCHI_MIZUCHI: ('miyadeguchi_mizuchi', ),
    MIYAKO_YOSHIKA: ('miyako_yoshika', ),
    MIZUHASHI_PARSEE: ('mizuhashi_parsee', ),
    MONONOBE_NO_FUTO: ('mononobe_no_futo', ),
    MORICHIKA_RINNOSUKE: ('morichika_rinnosuke', ),
    MORIYA_SUWAKO: ('moriya_suwako', ),
    MOTOORI_KOSUZU: ('motoori_kosuzu', ),
    MUGETSU: ('mugetsu_(touhou)', ),
    MURASA_MINAMITSU: ('murasa_minamitsu', ),
    NAGAE_IKU: ('nagae_iku', ),
    NAZRIN: ('nazrin', ),
    NIPPAKU_ZANMU: ('nippaku_zanmu', ),
    NISHIDA_SATONO: ('nishida_satono', ),
    NIWATARI_KUTAKA: ('niwatari_kutaka', ),
    NOROIKO: ('noroiko', ),
    OKAZAKI_YUMEMI : ('okazaki_yumemi', ),
    OKUNODA_MIYOI: ('okunoda_miyoi', ),
    ONOZUKA_KOMACHI: ('onozuka_komachi', ),
    ORANGE: ('orange_(touhou)', ),
    PATCHOULI_KNOWLEDGE: ('patchouli_knowledge', ),
    PRISMRIVER_LYRICA: ('lyrica_prismriver', ),
    PRISMRIVER_LUNASA: ('lunasa_prismriver', ),
    PRISMRIVER_MERLIN: ('merlin_prismriver', ),
    PRISMRIVER_LAYLA: ('layla_prismriver ', ),
    HECATIA_LAPISLAZULI: ('hecatia_lapislazuli', ),
    REISEN_UDONGEIN_INABA: ('reisen_udongein_inaba', ),
    REIUJI_UTSUHO: ('reiuji_utsuho', ),
    RIKA: ('rika_(touhou)', ),
    RENGETEKI: ('rengeteki_(touhou)', ),
    WRIGGLE_NIGHTBUG: ('wriggle_nightbug', ),
    RINGO: ('ringo_(touhou)', ),
    RUUKOTO: ('ruukoto', ),
    LORELEI_MYSTIA: ('mystia_lorelei', ),
    RUMIA: ('rumia', ),
    SAIGYOUJI_YUYUKO: ('saigyouji_yuyuko', ),
    SAKATA_NEMUNO: ('sakata_nemuno', ),
    SARA: ('sara_(touhou)', ),
    SARIEL: ('sariel_(touhou)', ),
    SATOWA: ('girl_who_trained_on_mt._haku_(touhou)', ),
    SATSUKI_RIN: ('satsuki_rin', ),
    SCARLET_FLANDRE: ('flandre_scarlet', ),
    SCARLET_REMILIA: ('remilia_scarlet', ),
    SEIRAN: ('seiran_(touhou)', ),
    SEKIBANKI: ('sekibanki', ),
    SHAMEIMARU_AYA: ('shameimaru_aya', ),
    SHANGHAI: ('shanghai_doll', ),
    SHIKI_EIKI_YAMAXANADU: ('shiki_eiki', ),
    SHINGYOKU: ('shingyoku_(touhou)', ),
    SHINKI: ('shinki',),
    SOGA_NO_TOJIKO: ('soga_no_tojiko', ),
    SOKRATES: ('sokrates_(touhou)',),
    SON_BITEN: ('son_biten', ),
    STAR_SAPPHIRE: ('star_sapphire', ),
    SUKUNA_SHINMYOUMARU: ('sukuna_shinmyoumaru', ),
    TAMATSUKURI_MISUMARU: ('tamatsukuri_misumaru', ),
    TATARA_KOGASA: ('tatara_kogasa', ),
    TEIREIDA_MAI: ('teireida_mai', ),
    TENKAJIN_CHIYARI: ('tenkajin_chiyari', ),
    TENKYUU_CHIMATA: ('tenkyuu_chimata', ),
    TOKIKO: ('tokiko_(touhou)', ),
    TOMOMI: ('hourai_girl_(touhou)', ),
    TORAMARU_SHOU: ('toramaru_shou', ),
    TOUTETSU_YUUMA: ('toutetsu_yuuma', ),
    TOYOSATOMIMI_NO_MIKO: ('toyosatomimi_no_miko', ),
    TSUBAME: ('purple-haired_oekaki_girl_(touhou)', ),
    TSUKUMO_BENBEN: ('tsukumo_benben', ),
    TSUKUMO_YATSUHASHI: ('tsukumo_yatsuhashi', ),
    UNNAMED_EXOTIC_GIRL_20000_HIT_GIRL: ('20000-hit_girl_(touhou)', ),
    UNNAMED_EXOTIC_GIRL_CLEANING_MAID: ('cleaning_maid_(touhou)', ),
    USAMI_RENKO: ('usami_renko', ),
    USAMI_SUMIREKO: ('usami_sumireko', ),
    USHIZAKI_URUMI: ('ushizaki_urumi', ),
    VIVIT: ('vivit',),
    WAKASAGIHIME: ('wakasagihime', ),
    WATATSUKI_NO_TOYOHIME: ('watatsuki_no_toyohime', ),
    WATATSUKI_NO_YORIHIME: ('watatsuki_no_yorihime', ),
    WAYOUSEI: ('wayousei_(touhou)', ),
    YAGOKORO_EIRIN: ('yagokoro_eirin', ),
    YAKUMO_RAN: ('yakumo_ran', ),
    YAKUMO_YUKARI: ('yakumo_yukari', ),
    YAMASHIRO_TAKANE: ('yamashiro_takane', ),
    YASAKA_KANAKO: ('yasaka_kanako', ),
    YATADERA_NARUMI: ('yatadera_narumi', ),
    YOMOTSU_HISAMI: ('yomotsu_hisami', ),
    YORIGAMI_JOON: ('yorigami_jo\'on', ),
    YORIGAMI_SHION: ('yorigami_shion', ),
    YORUMI: ('moonlight\'s_anti-soul_(touhou)', ),
    YUKI: ('yuki_(touhou)', ),
    YUMEKO: ('yumeko_(touhou)', ),
    YUUGEN_MAGAN: ('yuugenmagan', ),
}
