__all__ = ()


ICON_KIND_AVATAR = 1
ICON_KIND_BANNER = 2

ICON_SOURCE_LOCAL = 1
ICON_SOURCE_GLOBAL = 2
ICON_SOURCE_GUILD = 3
ICON_SOURCE_DEFAULT = 4

ICON_KINDS_RP_GROUP = f'({ICON_KIND_AVATAR}|{ICON_KIND_BANNER})'
ICON_SOURCE_RP_GROUP = f'({ICON_SOURCE_LOCAL}|{ICON_SOURCE_GLOBAL}|{ICON_SOURCE_GUILD}|{ICON_SOURCE_DEFAULT})'


ICON_SOURCES = {
    'local' : ICON_SOURCE_LOCAL,
    'guild': ICON_SOURCE_GUILD,
    'global': ICON_SOURCE_GLOBAL,
    'default': ICON_SOURCE_DEFAULT,
}

ICON_SOURCES_REVERSED = {value: key for key, value in ICON_SOURCES.items()}

ICON_KINDS = {
    'avatar': ICON_KIND_AVATAR,
    'banner': ICON_KIND_BANNER,
}

ICON_KINDS_REVERSED = {value: key for key, value in ICON_KINDS.items()}
