__all__ = ()

from hata import BUILTIN_EMOJIS

from ..expression_tracking import ACTION_TYPE_EMOJI_CONTENT, ACTION_TYPE_EMOJI_REACTION, ACTION_TYPE_STICKER


MODE_NONE = 0
MODE_GUILD_OF = 1
MODE_GUILD_IN = 2


VALID_MODES = (
    MODE_GUILD_OF,
    MODE_GUILD_IN,
)


VALID_ACTION_TYPE_COMBINATIONS_PACKED = (
    1 << ACTION_TYPE_EMOJI_CONTENT,
    1 << ACTION_TYPE_EMOJI_REACTION,
    1 << ACTION_TYPE_STICKER,
    (1 << ACTION_TYPE_EMOJI_CONTENT) | (1 << ACTION_TYPE_EMOJI_REACTION),
)



EMOJI_PAGE_PREVIOUS = BUILTIN_EMOJIS['arrow_left']
EMOJI_PAGE_NEXT = BUILTIN_EMOJIS['arrow_right']
EMOJI_CLOSE = BUILTIN_EMOJIS['x']
