__all__ = ('CHAPTER_RULES', 'CHAPTER_STYLES', 'CHAPTERS', 'DUNGEON_SWEEPER_GAMES', 'SKILLS', 'STAGES',)

from hata import  Color, Emoji

CHAPTER_RULES = {}
CHAPTER_STYLES = {}
CHAPTERS = {}
SKILLS = {}
STAGES = {}


DUNGEON_SWEEPER_COLOR = Color(0xa000c4)
DUNGEON_SWEEPER_GAMES = {}
COLOR_TUTORIAL = Color(0xa000c4)
DIFFICULTY_COLORS = dict(enumerate((COLOR_TUTORIAL, Color(0x00cc03), Color(0xffe502), Color(0xe50016))))
DIFFICULTY_NAME_DEFAULT = '???'
DIFFICULTY_NAMES = dict(enumerate(('Tutorial', 'Easy', 'Normal', 'Hard',)))
STAGE_STEP_MULTI_STEP_BUTTON = 10

EMOJI_KOISHI_WAVE = Emoji.precreate(648173118392762449)

UI_TIMEOUT = 600.0
MAX_RENDER_EMOJI = 150

UI_STATE_NONE = 0
UI_STATE_READY = 1
UI_STATE_EDITING = 2
UI_STATE_CANCELLING = 3
UI_STATE_CANCELLED = 4
UI_STATE_SWITCHING_CONTEXT = 5

UI_STATE_VALUE_TO_NAME = {
    UI_STATE_READY: 'ready',
    UI_STATE_EDITING: 'editing',
    UI_STATE_CANCELLING: 'cancelling',
    UI_STATE_CANCELLED: 'cancelled',
    UI_STATE_SWITCHING_CONTEXT: 'switching context',
}

RUNNER_STATE_IN_MENU = 1
RUNNER_STATE_IN_GAME = 2
RUNNER_STATE_END_SCREEN = 3
RUNNER_STATE_CLOSED = 4

RUNNER_STATE_VALUE_TO_NAME = {
    RUNNER_STATE_IN_MENU: 'menu',
    RUNNER_STATE_IN_GAME: 'playing',
    RUNNER_STATE_END_SCREEN: 'end screen',
    RUNNER_STATE_CLOSED: 'closed',
}


RATING_MAX = 5
RATINGS = ('S', 'A', 'B', 'C', 'D', 'E')
RATING_REWARDS = (750, 500, 400, 300, 200, 100)
NEW_RECORD_REWARD = 1000
