__all__ = ()

CUSTOM_ID_BASE = 'ds.game.'

CUSTOM_ID_EMPTY_0 = CUSTOM_ID_BASE + 'I'
CUSTOM_ID_EMPTY_1 = CUSTOM_ID_BASE + 'J'
CUSTOM_ID_EMPTY_2 = CUSTOM_ID_BASE + 'K'
CUSTOM_ID_EMPTY_3 = CUSTOM_ID_BASE + 'L'


CUSTOM_ID_END_SCREEN_NEXT_STAGE = CUSTOM_ID_BASE + 'F'
CUSTOM_ID_END_SCREEN_RETURN_TO_MENU = CUSTOM_ID_BASE + 'G'
CUSTOM_ID_END_SCREEN_RESTART_STAGE = CUSTOM_ID_BASE + 'H'


CUSTOM_ID_IN_GAME_BACK = CUSTOM_ID_BASE + 'C'
CUSTOM_ID_IN_GAME_RESTART = CUSTOM_ID_BASE + 'D'
CUSTOM_ID_IN_GAME_RETURN_TO_MENU = CUSTOM_ID_BASE + 'E'
CUSTOM_ID_IN_GAME_SKILL = CUSTOM_ID_BASE + '0'

CUSTOM_ID_IN_GAME_WEST = CUSTOM_ID_BASE + '8'
CUSTOM_ID_IN_GAME_NORTH = CUSTOM_ID_BASE + '9'
CUSTOM_ID_IN_GAME_SOUTH = CUSTOM_ID_BASE + 'A'
CUSTOM_ID_IN_GAME_EAST = CUSTOM_ID_BASE + 'B'

CUSTOM_ID_IN_GAME_NORTH_TO_EAST = CUSTOM_ID_BASE + 'M'
CUSTOM_ID_IN_GAME_NORTH_TO_WEST = CUSTOM_ID_BASE + 'N'
CUSTOM_ID_IN_GAME_SOUTH_TO_EAST = CUSTOM_ID_BASE + 'O'
CUSTOM_ID_IN_GAME_SOUTH_TO_WEST = CUSTOM_ID_BASE + 'P'

CUSTOM_ID_IN_GAME_EAST_TO_NORTH = CUSTOM_ID_BASE + 'Q'
CUSTOM_ID_IN_GAME_EAST_TO_SOUTH = CUSTOM_ID_BASE + 'R'
CUSTOM_ID_IN_GAME_WEST_TO_NORTH = CUSTOM_ID_BASE + 'S'
CUSTOM_ID_IN_GAME_WEST_TO_SOUTH = CUSTOM_ID_BASE + 'T'


CUSTOM_ID_IN_MENU_STAGE_NEXT = CUSTOM_ID_BASE + '1'
CUSTOM_ID_IN_MENU_STAGE_PREVIOUS = CUSTOM_ID_BASE + '2'
CUSTOM_ID_IN_MENU_STAGE_NEXT_MULTI = CUSTOM_ID_BASE + '3'
CUSTOM_ID_IN_MENU_STAGE_PREVIOUS_MULTI = CUSTOM_ID_BASE + '4'
CUSTOM_ID_IN_MENU_CHAPTER_NEXT = CUSTOM_ID_BASE + '5'
CUSTOM_ID_IN_MENU_CHAPTER_PREVIOUS = CUSTOM_ID_BASE + '6'
CUSTOM_ID_IN_MENU_SELECT_STAGE = CUSTOM_ID_BASE + '7'
CUSTOM_ID_IN_MENU_CLOSE = CUSTOM_ID_BASE + 'V'


CUSTOM_ID_RULES_SELECT = CUSTOM_ID_BASE + 'U'
