__all__ = ()

BIT_FLAG_NORTH            = 1 << 12
BIT_FLAG_EAST             = 1 << 13
BIT_FLAG_SOUTH            = 1 << 14
BIT_FLAG_WEST             = 1 << 15


BIT_MASK_FLOOR              = 1 << 0
BIT_MASK_WALL               = 1 << 1
BIT_MASK_CHARACTER          = 1 << 2
BIT_MASK_HOLE               = 1 << 3
BIT_MASK_HOLE_FILLED        = 1 << 4
BIT_MASK_OBSTACLE           = 1 << 5
BIT_MASK_OBSTACLE_DESTROYED = 1 << 6
BIT_MASK_TARGET             = 1 << 7
BIT_MASK_BOX                = 1 << 8


BIT_MASK_PASSABLE = BIT_MASK_FLOOR | BIT_MASK_HOLE_FILLED | BIT_MASK_OBSTACLE_DESTROYED | BIT_MASK_TARGET
BIT_MASK_PUSHABLE = BIT_MASK_BOX
BIT_MASK_UNPUSHABLE = BIT_MASK_WALL | BIT_MASK_HOLE | BIT_MASK_OBSTACLE
BIT_MASK_TARGET_ON_FLOOR = BIT_MASK_TARGET | BIT_MASK_FLOOR
BIT_MASK_BOX_ON_TARGET = BIT_MASK_BOX | BIT_MASK_TARGET | BIT_MASK_FLOOR
BIT_MASK_BOX_ON_HOLE_FILLED = BIT_MASK_BOX | BIT_MASK_HOLE_FILLED
BIT_MASK_BOX_ON_OBSTACLE_DESTROYED = BIT_MASK_BOX | BIT_MASK_OBSTACLE_DESTROYED
BIT_MASK_ALIGN_ALL = BIT_FLAG_NORTH | BIT_FLAG_EAST | BIT_FLAG_SOUTH | BIT_FLAG_WEST

BIT_MASK_JUMPABLE = BIT_MASK_BOX | BIT_MASK_HOLE
BIT_MASK_OCCUPIED = BIT_MASK_WALL | BIT_MASK_PUSHABLE | BIT_MASK_OBSTACLE
