__all__ = ()

WELCOME_MESSAGES = (
    'Roses are red, also blue, {user} joined this server with Mr. Hat too',
    'Koooosh. {user} just landed.',
    '{user} just joined. Everyone, watch your back!',
    'Welcome, {user}. We hope you brought shrimp fry.',
    'Where’s {user}? RIGHT BEHIND YOU!',
    'Heart throbbing {user} showed up!',
    'It\'s a youkai! It\'s a fairy! Nevermind, it\'s just {user}.',
    'We\'ve been already behind you {user}',
    'It\'s {user}! Praise Mr. Unconsciousness! [T]/',
    'Always gonna love {user}. Always gonna remember {user}.',
    '{user} is here to stab and eat shrimp fry. And {user} is all out of shrimp fry.',
    '{user} is behind me... or are they?',
    '{user} just showed up. Hold my fishing rod.',
    'A lovely {user} chan appeared.',
    '{user} just joined. Can I get a croissant?',
    'Mr. Hat owner {user}',
    '{user} is here, as the Mr. Hat foretold.',
    '{user} just arrived. Seems adorable - please love.',
    'Moshi Moshi?. Is it {user} you\'re calling?',
    'The creature {user} showed up!',
    'Ready to stop thinking, {user}?',
    '{user} has joined the server! It\'s a fumo!',
    '{user} just joined the server - *staaaare*',
    '{user} just joined. Everyone, stop thinking!',
    'Welcome, {user}. Bring shrimp fry and croissant.',
    'Satoooori, {user} is here!',
    '{user} has arrived. The dinner just started.',
    'Welcome, {user}. Stay awhile and fish with us.',
    'Welcome {user}. Leave your Mr. Knife by the door.',
    '{user} joined. Mr. Hat helps them relax.',
    '{user} just arrived. Seems conscious - please nerf.',
    '{user} has joined the Extra stage.',
    'Hey! Listen! {user} has called!',
    '{user} hopped into the server. My face is butter!!',
    '{user} just flew into the server.',
    'Yay! {user} just landed.',
    '{user} joined. You must collect additional **P**ower items.',
)
