__all__ = (
    'AUTOMATION_CONFIGURATIONS', 'COMMUNITY_MESSAGE_MODERATION_AVAILABILITY_DURATION_DEFAULT',
    'COMMUNITY_MESSAGE_MODERATION_AVAILABILITY_DURATION_MAX', 'COMMUNITY_MESSAGE_MODERATION_AVAILABILITY_DURATION_MIN',
    'COMMUNITY_MESSAGE_MODERATION_DOWN_VOTE_EMOJI_DEFAULT', 'COMMUNITY_MESSAGE_MODERATION_DOWN_VOTE_EMOJI_ID_DEFAULT',
    'COMMUNITY_MESSAGE_MODERATION_VOTE_THRESHOLD_DEFAULT', 'COMMUNITY_MESSAGE_MODERATION_VOTE_THRESHOLD_MAX',
    'COMMUNITY_MESSAGE_MODERATION_VOTE_THRESHOLD_MIN'
)

from hata import BUILTIN_EMOJIS


AUTOMATION_CONFIGURATIONS = {}
SATORI_CHANNELS = {}


COMMUNITY_MESSAGE_MODERATION_AVAILABILITY_DURATION_DEFAULT = 3600
COMMUNITY_MESSAGE_MODERATION_AVAILABILITY_DURATION_MIN = 30
COMMUNITY_MESSAGE_MODERATION_AVAILABILITY_DURATION_MAX = 3600
COMMUNITY_MESSAGE_MODERATION_DOWN_VOTE_EMOJI_DEFAULT = BUILTIN_EMOJIS['x']
COMMUNITY_MESSAGE_MODERATION_DOWN_VOTE_EMOJI_ID_DEFAULT = COMMUNITY_MESSAGE_MODERATION_DOWN_VOTE_EMOJI_DEFAULT.id
COMMUNITY_MESSAGE_MODERATION_VOTE_THRESHOLD_DEFAULT = 4
COMMUNITY_MESSAGE_MODERATION_VOTE_THRESHOLD_MIN = 2
COMMUNITY_MESSAGE_MODERATION_VOTE_THRESHOLD_MAX = 100
