__all__ = ()


ACHIEVEMENTS = (
    '100% Orange Juice',
    'Pudding Chaser',
    'Hyper',
    'A Little Aviator',
    'Penny Pincher',
    'Poppo?',
    'Superstar',
    'Booster Pack',
    'Collector',
    'Card Shark',
    'Card Sage',
    'People Watching',
    'Not Playing with a Full Deck of Cards',
    'Nice Present',
    'Shiny!',
    'Poppo Always Wins',
    'Little Wars',
    'Starbound',
    'Tougher Than Diamond',
    'Your Home Is My Home',
    'And Away They Went',
    'Banned for Life',
    'Full Metal Brother',
    'Moving Castle in the Sky',
    'Mimyuu\'s Hammer',
    'Definite Defender',
    'You Can Run...',
    'Fair Trade',
    'Some People Have All the Luck!',
    'The Girl Who Stole the Stars',
    'Unstoppable',
    'Pacifist',
    'Duelist',
    'Battle Master',
    'Vendetta',
    'Bit by Bit',
    'Fully Deployed',
    'Orders Are Absolute',
    'Chicken Parade',
    'Beyond Hell',
    'End of Pudding',
    'Saki\'s Cookie',
    'The Big Bang',
    'Dropped the Bomb',
    'Seeking Kyupita',
    'Liberated',
    'Kiss from a Rose',
    'Waylaid',
    'Changeling',
    'Hard Counter',
    'A Tight Budget',
    'A Side Order of Chicken',
    'The Long Run',
    'Mad Dash',
    'Turned Tables',
    'Put It on the Bill',
    'Denizen of Darkness',
    'Plushie Master',
    'Dance of the Beasts',
    'Battle Addict',
    'All Ablaze',
    'Better to Burn Out',
    'Planned Demolition',
    'Full Payload',
    'Rebellion',
    'A Cool Beauty',
    'Total Barrier',
    'You Call That a Trap?',
    'Cutie',
    'Tag Team',
    'Taking You Home',
    'Free Spirit',
    'A Whimsical Beatdown',
    'Combat Flight',
    'Champion of War',
    'Unbreakable',
    'A Long Fuse',
    'Proof of the Pudding',
    'Champion of Peace',
    'Source of Conflict',
    'The Traditional Way',
    'A Sweet Ending',
    'Riding the Blast Wave',
    'Fully Accelerated',
    'Gentleman\'s Victory',
    'Miser',
    'Lost And Found',
    'Who Put This Here?',
    'They See Me Rolling',
    'Quick Fix',
    'In a Burst of Light',
    'Ultimate Weapon',
    'Ultimate Destruction',
    'All Systems Go',
    'We Are Waruda',
    'Bad Kids\' Usurpation',
    'Spy Games',
    'Not a Real Medical License',
    'The Doctor is Out',
    'Lingering Effects',
    'Master of Thighs',
    'Man\'s Best Friend',
    'Ahead of the Game',
    'Feeling Blue',
    'Float Like a Butterfly',
    'Just a Lock of Hair',
    'Cheerful Green',
    'Can Take a Pummeling',
    'Slightly Dense',
    'Girl Power',
    'Extortion',
    'Poppo Stole the Precious Things',
    'Bounty Hunter',
    'Power Overwhelming',
    'Finding Friends',
    'Wild Party',
    'Big, Bigger, Po',
    'Priceless Treasure',
    'New Cat in the House',
    'Beastly Cunning',
    'Gone Pudding Gone',
    'Leisure Time',
    'Magical Miracle!',
    'A Fine Day to Stay in Bed',
    'Nanora!',
    'Can\'t see me, nyahaha!',
    'A Lot of Rocks',
    'Oh, Tequila',
    'A Pirate I Was Meant to Be',
    'Pirate\'s Booty',
    'Troublemaker',
    'Red vs Blue',
    'Pumpkin Smasher',
    'Nacchan',
    'True Feast',
    'Master Chef',
    'Santa\'s Little Menace',
    'A Hyper Bunny',
    'Nico\'s Presents!',
    'Working Dad',
    'Welcome to the Toy Store',
    'Record Sales',
    'Crossed Christmases',
    'Fun and Games',
    'Lucky Draw',
    'Trophy Collector',
    'Tomboy',
    'Heavy Duty',
    'Strike Force One',
    'Say Our Name',
    'Mark of a Hero',
    'Smoke and Mirrors',
    'Roost',
    'Savage Talons',
    'Malfunction',
    'Imaginary Numbers',
    'Star Mania',
    'Death and Taxes',
    'Power Through',
    'Steady Does it',
    'Just a Small Scratch',
    'Taste of Revenge',
    'Animal Farm',
    'Efficiency Theory',
    'Value Judgment',
    'Ultimate Duet',
    'Full House',
    'A New Star is Born',
    'Twilight of the Beasts',
    'A Perfect Maneuver',
    'Poppoception',
    'Pranked',
    'Sticky Fingers',
    'Can Always Go Faster',
    'Fun in the Sun',
    'A Midsummer Night\'s Dream',
    'Total Rampage',
    'Summer Games',
    'Creatures of Excellence',
    'Who Flies Highest',
    'Fighting the Windmills',
    'Master of Puppets',
    'Voice of Punishment',
    'Voice of Healing',
    'Guild Mate',
    'The Cross of Battle',
    'Rivalry',
    'A Pack of Pudding',
    'The Odds Paid Off',
    'Serious Fire Support',
    'Dirty Business',
    'Bound by Destiny',
    'Loved by Fans',
    'Lucky Streak',
    'A Big Mix-up',
    'Big Po\'s Special',
    'Redemption Story',
    'Master of the Minions',
    'Mama Knows Best',
    'A Magical BBQ',
    'Guardian of a Lost Planet',
    'With Great Power...',
    'With Age Comes Wisdom',
    'Sumika is Sumika',
    'Hyper Space Computing',
    'Sibling Rivalry',
    'Forest Witch',
    'Who Am I?',
    'Born Under a Lucky Star',
    'Eggs',
    'Mama\'s Girl',
    'Big Game Hunters',
    'Small Game Hunter',
    'Destined Meeting',
    'Witch of Speed',
    'Extra Motivated',
    'Fast Cut',
    'A Beast of a Witch',
    'Beast Friends',
    'Unruly Friend',
    'Treasure Hunter',
    'Weak Point',
    'Information Control',
    'Easily Aggravated',
    'Fuming Mad',
    'Closing Argument',
    'Welcome, Dear Customer!',
    'May I Take Your Order?',
    'Manageeeeeer!',
    'Dog Ears',
    'Mirror Image',
    'The Evil Is Sealed',
    'My Bodyguard May Be Clumsy But They Are Secretly the Strongest',
    'The Memoirs of a Living Armor',
    'How to Become a Max Level Bounty Hunter in the Starting Village',
    'That Time I Accidentally KO\'d the Demon Lord',
    'Other World Deliveryman',
    'A Famous Slime Slayer',
    'Jackpot',
    'Decisive Rearming',
    'Paid Overtime',
    'Monster Bird?',
    'Home Crasher',
    'Slick Moves',
    'Living Atlas',
    'Travel Guide of the Year',
    'Destination Unknown',
    'Fowl-Weather Friends',
    'Chickening Out',
    'Stuffed',
    'Hotrodder',
    'Pedal to the Metal',
    'Roadkill',
    'Never Lose Heart',
    'Money Makes the World Go \'Round',
    'No Refunds',
    'Afloat',
    'Training Day',
    'Rebellious Student',
    'Decorous Debutante',
    'Money Talks',
    'Hidden Potential',
    'Celestial Steps',
    'Moonwalk',
    'Lunatic Princess',
    'No Country for an Old Man',
    'Twilight Dreaming',
    'Master of the Guild',
    'The Littlest Aviator',
    'Taking Sides',
    'Quick Draw',
    'Mastermind',
    'World of Dreams',
    'Mending Bridges',
    'Reika of Stars',
    'Broken Promises',
    'Lucky Break',
    'Pet the Cat',
    'Watery Friend',
    'Et tu, Watty',
    'Splash Damage',
    'Top Dog',
    'Bomb-sniffing Pomeranius',
    'Well Treated',
    'Master of the Sweet Universe',
    'Creator\'s Whim',
    'Creator Giveth, Creator Taketh',
    'A Cheerful God',
    'Unsettled Argument',
    'Meet Your Maker',
    'Blogger of the Year',
    'Shop \'Til You Drop',
    'Signal Boosting',
    'Getting Festive',
    'And That\'s Terrible',
    'Had My Cake And Ate It Too',
    'Slumber Party of Darkness',
    'Tossing and Turning',
    'The Lion Sleeps Tonight',
    'Exemplary Behavior',
    'Catch Me if You Can',
    'In Plain Sight',
    'The Great Escape',
    'Mother Superior',
    'Mum\'s the Word',
    'Earthbound',
    'Beholden to Darkness',
    'Resisting the Call',
    'Lizard of Misfortune',
    'Wandering Heart',
    'Endless Punishment',
    'The Miracle is Unbreakable',
    'Zero to Hero',
    'The Boy and the Hero',
    'Second Wind',
    'Underdoggy',
    'Lost, Found and Lost Again',
    'My Strongest Warrior',
    'Revolutionary',
    'Delayed Deploy',
    'Bank of Poppo Always Wins',
    'A Jolly Good Fellow',
    'A Free Sky',
    'In a Spot of Trouble?',
    'Old Guard',
    'Worst Job Ever Done',
    'No Complaints Whatsoever',
    'Poyo Poyo',
    'New School, New Friends',
    'Instinct of a Beast',
    'Chuu Chuu',
    'A New Me',
    'Getting a Little Into It',
    'Good Cheer',
    'Party People',
    'Sign, Please!',
    'An Ordinary Genius',
    'Unmatched Intellect',
    'No Match for RNG',
    'Extracurricular Activity',
    'Burst Fire',
    'A Dish to Die for',
    'We Do a Little Thieving',
    'Comeback Story',
    'Not Only Fluffy',
    'Angry Tick',
    'Triple Trouble',
    'Vanguard of the Burning Sands',
    'And Make It Double',
    'Path of Most Resistance',
)
