__all__ = (
    'STAT_NAME_FULL_BEDROOM', 'STAT_NAME_FULL_CHARM', 'STAT_NAME_FULL_CUTENESS', 'STAT_NAME_FULL_HOUSEWIFE',
    'STAT_NAME_FULL_LOYALTY',
)

from collections import OrderedDict


STATS_CACHE = OrderedDict()
STATS_CACHE_SIZE_MAX = 100


STAT_NAME_FULL_HOUSEWIFE = 'Housewife capabilities'
STAT_NAME_FULL_CUTENESS = 'cuteness'
STAT_NAME_FULL_BEDROOM = 'bedroom skills'
STAT_NAME_FULL_CHARM = 'charm'
STAT_NAME_FULL_LOYALTY = 'loyalty'

STAT_NAME_SHORT_HOUSEWIFE = 'housewife'
STAT_NAME_SHORT_CUTENESS = 'cuteness'
STAT_NAME_SHORT_BEDROOM = 'bedroom'
STAT_NAME_SHORT_CHARM = 'charm'
STAT_NAME_SHORT_LOYALTY = 'loyalty'

