__all__ = ()


RELATIONSHIP_TYPE_NONE = 0
RELATIONSHIP_TYPE_UNSET = 1
RELATIONSHIP_TYPE_WAIFU = 2
RELATIONSHIP_TYPE_SISTER_LIL = 3
RELATIONSHIP_TYPE_SISTER_BIG = 4
RELATIONSHIP_TYPE_MAMA = 5
RELATIONSHIP_TYPE_MASTER = 6
RELATIONSHIP_TYPE_MAID = 7
RELATIONSHIP_TYPE_DAUGHTER = 8

RELATIONSHIP_TYPE_NAME_DEFAULT = 'pudding'

RELATIONSHIP_TYPE_NAMES = {
    RELATIONSHIP_TYPE_NONE: RELATIONSHIP_TYPE_NAME_DEFAULT,
    RELATIONSHIP_TYPE_UNSET: 'unset',
    RELATIONSHIP_TYPE_WAIFU: 'waifu',
    RELATIONSHIP_TYPE_SISTER_LIL: 'little sister',
    RELATIONSHIP_TYPE_SISTER_BIG: 'big sister',
    RELATIONSHIP_TYPE_MAMA: 'mama',
    RELATIONSHIP_TYPE_MASTER: 'master',
    RELATIONSHIP_TYPE_MAID: 'maid',
    RELATIONSHIP_TYPE_DAUGHTER: 'daughter',
}

RELATIONSHIP_TYPE_RELATIONSHIPS = {
    RELATIONSHIP_TYPE_UNSET: RELATIONSHIP_TYPE_UNSET,
    RELATIONSHIP_TYPE_WAIFU: RELATIONSHIP_TYPE_WAIFU,
    RELATIONSHIP_TYPE_SISTER_LIL: RELATIONSHIP_TYPE_SISTER_BIG,
    RELATIONSHIP_TYPE_SISTER_BIG: RELATIONSHIP_TYPE_SISTER_LIL,
    RELATIONSHIP_TYPE_MAMA: RELATIONSHIP_TYPE_DAUGHTER,
    RELATIONSHIP_TYPE_DAUGHTER: RELATIONSHIP_TYPE_MAMA,
    RELATIONSHIP_TYPE_MASTER: RELATIONSHIP_TYPE_MAID,
    RELATIONSHIP_TYPE_MAID: RELATIONSHIP_TYPE_MASTER,
}


def get_relationship_type_name(relationship_type):
    """
    Gets the relationship type's name.
    
    Parameters
    ----------
    relationship_type : `int`
        Relationship type.
    
    Returns
    -------
    relationship_type_name : `str`
    """
    return RELATIONSHIP_TYPE_NAMES.get(relationship_type, RELATIONSHIP_TYPE_NAME_DEFAULT)


RELATIONSHIP_REQUEST_CREATABLE = {
    'marry': RELATIONSHIP_TYPE_WAIFU,
    'blood-pact' : RELATIONSHIP_TYPE_SISTER_BIG,
    'adopt': RELATIONSHIP_TYPE_MAMA,
    'hire': RELATIONSHIP_TYPE_MASTER,
}
