__all__ = ()

AUTO_CANCELLATION_CONDITION_ID_LESS_THAN = 1
AUTO_CANCELLATION_CONDITION_ID_LESS_OR_EQUAL = 2
AUTO_CANCELLATION_CONDITION_ID_EQUAL = 3
AUTO_CANCELLATION_CONDITION_ID_NOT_EQUAL = 4
AUTO_CANCELLATION_CONDITION_ID_GREATER_OR_EQUAL = 5
AUTO_CANCELLATION_CONDITION_ID_GREATER_THAN = 6
