__all__ = (
    'AUTO_CANCELLATION_ID_DEFAULT', 'AUTO_CANCELLATION_ID_LOOT_LOST_ONCE', 'AUTO_CANCELLATION_ID_LOW_ENERGY_OR_HEALTH',
    'AUTO_CANCELLATION_ID_NEVER'
)

AUTO_CANCELLATION_ID_DEFAULT = 1
AUTO_CANCELLATION_ID_NEVER = 2
AUTO_CANCELLATION_ID_LOOT_LOST_ONCE = 3
AUTO_CANCELLATION_ID_LOW_ENERGY_OR_HEALTH = 4
