__all__ = ()

from itertools import count
from math import floor
from time import time

from hata import BUILTIN_EMOJIS, create_button, create_row

COUNTER_MASK = (1 << 32) - 1
STARTUP_IDENTIFIER = (floor(time()) & COUNTER_MASK) << 32
COUNTER = iter(count(0))


CARD_TYPES = (
    BUILTIN_EMOJIS['spades'].as_emoji,
    BUILTIN_EMOJIS['clubs'].as_emoji,
    BUILTIN_EMOJIS['hearts'].as_emoji,
    BUILTIN_EMOJIS['diamonds'].as_emoji,
)

CARD_NUMBERS = (
    BUILTIN_EMOJIS['two'].as_emoji,
    BUILTIN_EMOJIS['three'].as_emoji,
    BUILTIN_EMOJIS['four'].as_emoji,
    BUILTIN_EMOJIS['five'].as_emoji,
    BUILTIN_EMOJIS['six'].as_emoji,
    BUILTIN_EMOJIS['seven'].as_emoji,
    BUILTIN_EMOJIS['eight'].as_emoji,
    BUILTIN_EMOJIS['nine'].as_emoji,
    BUILTIN_EMOJIS['keycap_ten'].as_emoji,
    BUILTIN_EMOJIS['regional_indicator_j'].as_emoji,
    BUILTIN_EMOJIS['regional_indicator_q'].as_emoji,
    BUILTIN_EMOJIS['regional_indicator_k'].as_emoji,
    BUILTIN_EMOJIS['a'].as_emoji,
)

DECK_SIZE = len(CARD_TYPES) * len(CARD_NUMBERS)
ACE_INDEX = len(CARD_NUMBERS) - 1
BET_MIN = 10
PLAYERS_MAX = 10


GAME_21_EMOJI_NEW = BUILTIN_EMOJIS['new']
GAME_21_EMOJI_STOP = BUILTIN_EMOJIS['octagonal_sign']

GAME_21_CUSTOM_ID_NEW = '21.new'
GAME_21_CUSTOM_ID_STOP = '21.stop'

GAME_21_BUTTON_NEW_ENABLED = create_button(
    emoji = GAME_21_EMOJI_NEW,
    custom_id = GAME_21_CUSTOM_ID_NEW,
)

GAME_21_BUTTON_NEW_DISABLED = GAME_21_BUTTON_NEW_ENABLED.copy_with(
    enabled = False,
)

GAME_21_BUTTON_STOP_ENABLED = create_button(
    emoji = GAME_21_EMOJI_STOP,
    custom_id = GAME_21_CUSTOM_ID_STOP,
)

GAME_21_BUTTON_STOP_DISABLED = GAME_21_BUTTON_STOP_ENABLED.copy_with(
    enabled = False,
)

GAME_21_ROW_ENABLED = create_row(
    GAME_21_BUTTON_NEW_ENABLED,
    GAME_21_BUTTON_STOP_ENABLED,
)

GAME_21_ROW_DISABLED = create_row(
    GAME_21_BUTTON_NEW_DISABLED,
    GAME_21_BUTTON_STOP_DISABLED,
)


GAME_21_EMOJI_ENTER = BUILTIN_EMOJIS['hand_splayed']
GAME_21_EMOJI_START = BUILTIN_EMOJIS['ok_hand']
GAME_21_EMOJI_CANCEL = BUILTIN_EMOJIS['x']

GAME_21_CUSTOM_ID_ENTER = '21.enter'
GAME_21_CUSTOM_ID_START = '21.start'
GAME_21_CUSTOM_ID_CANCEL = '21.cancel'

GAME_21_BUTTON_ENTER_ENABLED = create_button(
    emoji = GAME_21_EMOJI_ENTER,
    custom_id = GAME_21_CUSTOM_ID_ENTER,
)

GAME_21_BUTTON_ENTER_DISABLED = GAME_21_BUTTON_ENTER_ENABLED.copy_with(
    enabled = False,
)

GAME_21_BUTTON_START_ENABLED = create_button(
    emoji = GAME_21_EMOJI_START,
    custom_id = GAME_21_CUSTOM_ID_START,
)

GAME_21_BUTTON_START_DISABLED = GAME_21_BUTTON_START_ENABLED.copy_with(
    enabled = False,
)

GAME_21_BUTTON_CANCEL_ENABLED = create_button(
    emoji = GAME_21_EMOJI_CANCEL,
    custom_id = GAME_21_CUSTOM_ID_CANCEL,
)

GAME_21_BUTTON_CANCEL_DISABLED = GAME_21_BUTTON_CANCEL_ENABLED.copy_with(
    enabled = False,
)

GAME_21_JOIN_ROW_ENABLED = create_row(
    GAME_21_BUTTON_ENTER_ENABLED,
    GAME_21_BUTTON_START_ENABLED,
    GAME_21_BUTTON_CANCEL_ENABLED,
)

GAME_21_JOIN_ROW_FULL = create_row(
    GAME_21_BUTTON_ENTER_DISABLED,
    GAME_21_BUTTON_START_ENABLED,
    GAME_21_BUTTON_CANCEL_ENABLED,
)

GAME_21_JOIN_ROW_DISABLED = create_row(
    GAME_21_BUTTON_ENTER_DISABLED,
    GAME_21_BUTTON_START_DISABLED,
    GAME_21_BUTTON_CANCEL_DISABLED,
)

PLAYER_STATE_NONE = 0
PLAYER_STATE_FINISH = 1
PLAYER_STATE_INITIALIZATION_ERROR = 2 
PLAYER_STATE_IN_GAME_ERROR = 3
PLAYER_STATE_CANCELLED_TIMEOUT = 4 
PLAYER_STATE_CANCELLED_UNKNOWN = 5
PLAYER_STATE_CANCELLED_BY_USER = 6


GAME_21_RUNNER_TIMEOUT = 300.0
GAME_21_JOINER_TIMEOUT = 300.0


UI_STATE_NONE = 0
UI_STATE_READY = 1
UI_STATE_EDITING = 2
UI_STATE_CANCELLING = 3
UI_STATE_CANCELLED = 4
UI_STATE_SWITCHING_CONTEXT = 5


SESSIONS = {}
