__all__ = ()

from struct import Struct

from hata import BUILTIN_EMOJIS


CONTENT_LENGTH_MAX = 250
CONTENT_LENGTH_TRUNCATE_AFTER = 200
CONTENT_LENGTH_SPACE_SEARCH_AREA = 50

ENTRY_PAGE_SIZE = 6
ITEMS_MAX = 20
ENTRIES_MAX = 20


EMOJI_PAGE_DECREMENT = BUILTIN_EMOJIS['arrow_left']
EMOJI_PAGE_INCREMENT = BUILTIN_EMOJIS['arrow_right']

ENTRY_DATA_VERSION = 1

AUTOMATION_REACTION_ROLE_BY_GUILD_ID = {}
AUTOMATION_REACTION_ROLE_BY_MESSAGE_ID = {}

MESSAGE_SYNC_TASKS = {}

MESSAGE_SYNC_RESULT_SUCCESS = 0
MESSAGE_SYNC_RESULT_TEMPORARY_FAILURE = 1
MESSAGE_SYNC_RESULT_DELETED = 2


AUTOMATION_REACTION_ROLE_ENTRY_DATA_VERSION_1_HEAD_STRUCT = Struct('<Qbb')
AUTOMATION_REACTION_ROLE_ENTRY_DATA_VERSION_1_ROLE_IDS_STRUCT = Struct('<Q')
