__all__ = ()

from collections import OrderedDict

from scarletio import WeakValueDictionary


RELATIONSHIP_CACHE = WeakValueDictionary()
RELATIONSHIP_SAVE_TASKS = {}
RELATIONSHIP_LISTING_GET_QUERY_TASKS = {}
RELATIONSHIP_LISTING_CACHE = OrderedDict()
RELATIONSHIP_LISTING_CACHE_SIZE_MAX = 100


RELATIONSHIP_REQUEST_CACHE = WeakValueDictionary()
RELATIONSHIP_REQUEST_QUERY_TASKS = {}
RELATIONSHIP_REQUEST_SAVE_TASKS = {}
RELATIONSHIP_REQUEST_LISTING_GET_QUERY_TASKS = {}
RELATIONSHIP_REQUEST_LISTING_CACHE = OrderedDict()
RELATIONSHIP_REQUEST_LISTING_CACHE_SIZE_MAX = 100


ACTION_NAME_UNKNOWN = 'pudding'
ACTION_NAME_UNKNOWN_CAPITALISED = 'Pudding'

