__all__ = ()

from hata import BUILTIN_EMOJIS

from ..item_core import (
    ITEM_FLAG_COSTUME, ITEM_FLAG_EDIBLE, ITEM_FLAG_HEAD, ITEM_FLAG_NPC, ITEM_FLAG_SPECIES, ITEM_FLAG_WEAPON
)


ITEM_CATEGORY_CHOICES = [
    ('all', 0),
    ('costume', ITEM_FLAG_COSTUME),
    ('edible', ITEM_FLAG_EDIBLE),
    ('head accessory', ITEM_FLAG_HEAD),
    ('weapon', ITEM_FLAG_WEAPON),
]


DISABLED_ITEM_FLAGS = ITEM_FLAG_NPC | ITEM_FLAG_SPECIES

DURATION_DAYS_THRESHOLD_LOWER = 2
DURATION_DAYS_THRESHOLD_UPPER = 8
DURATION_DAYS_DEFAULT = 5

PAGE_SIZE_DEFAULT = 10
SELL_FEE = 0.01

EMOJI_LEFT = BUILTIN_EMOJIS['arrow_backward']
EMOJI_RIGHT = BUILTIN_EMOJIS['arrow_forward']
EMOJI_CLOSE = BUILTIN_EMOJIS['x']

BID_INCREASE_LOWER_THRESHOLD = 10
BID_INCREASE_REQUIRED_RATIO = 0.01
