__all__ = ('LOCATIONS_ALLOWED',)

from ..constants import LOCATIONS
from ..target import (
    TARGET_ID_BAMBOO_FOREST_FORAGING, TARGET_ID_EIENTEI_MANSION_GARDENING, TARGET_ID_HAKUGYOKUROU_MANSION_GARDENING,
    TARGET_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_CARROT, TARGET_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_GARLIC,
    TARGET_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_SCARLET_ONION, TARGET_ID_HUMAN_VILLAGE_VINEYARDS_GARDENING_GRAPE,
    TARGET_ID_MORIYA_SHRINE_FORAGING, TARGET_ID_RUINS_FORAGING
)

from .location import Location
from .location_ids import (
    LOCATION_ID_BAMBOO_FOREST, LOCATION_ID_EIENTEI_MANSION, LOCATION_ID_HAKUGYOKUROU_MANSION,
    LOCATION_ID_HUMAN_VILLAGE_OUTSKIRTS, LOCATION_ID_HUMAN_VILLAGE_VINEYARDS, LOCATION_ID_MORIYA_SHRINE,
    LOCATION_ID_RUINS
)


LOCATION_HUMAN_VILLAGE_OUTSKIRTS = LOCATIONS[LOCATION_ID_HUMAN_VILLAGE_OUTSKIRTS] = Location(
    LOCATION_ID_HUMAN_VILLAGE_OUTSKIRTS,
    'Human village outskirts',
    600,
    (
        TARGET_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_CARROT,
        TARGET_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_GARLIC,
        TARGET_ID_HUMAN_VILLAGE_OUTSKIRTS_GARDENING_SCARLET_ONION,
    ),
)


LOCATION_HUMAN_VILLAGE_VINEYARDS = LOCATIONS[LOCATION_ID_HUMAN_VILLAGE_VINEYARDS] = Location(
    LOCATION_ID_HUMAN_VILLAGE_VINEYARDS,
    'Human village vineyards',
    1200,
    (
        TARGET_ID_HUMAN_VILLAGE_VINEYARDS_GARDENING_GRAPE,
    ),
)

LOCATION_RUINS = LOCATIONS[LOCATION_ID_RUINS] = Location(
    LOCATION_ID_RUINS,
    'Ruins',
    6600,
    (
        TARGET_ID_RUINS_FORAGING,
    ),
)


LOCATION_EIENTEI_MANSION = LOCATIONS[LOCATION_ID_EIENTEI_MANSION] = Location(
    LOCATION_ID_EIENTEI_MANSION,
    'Eientei mansion',
    4100,
    (
        TARGET_ID_EIENTEI_MANSION_GARDENING,
    ),
)


LOCATION_BAMBOO_FOREST = LOCATIONS[LOCATION_ID_BAMBOO_FOREST] = Location(
    LOCATION_ID_BAMBOO_FOREST,
    'Bamboo forest',
    3600,
    (
        TARGET_ID_BAMBOO_FOREST_FORAGING,
    ),
)


LOCATION_MORIYA_SHRINE = LOCATIONS[LOCATION_ID_MORIYA_SHRINE] = Location(
    LOCATION_ID_MORIYA_SHRINE,
    'Moriya shrine',
    15300,
    (
        TARGET_ID_MORIYA_SHRINE_FORAGING,
    ),
)


LOCATION_HAKUGYOKUROU_MANSION = LOCATIONS[LOCATION_ID_HAKUGYOKUROU_MANSION] = Location(
    LOCATION_ID_HAKUGYOKUROU_MANSION,
    'Hakugyokurou Mansion',
    12600,
    (
        TARGET_ID_HAKUGYOKUROU_MANSION_GARDENING,
    ),
)


LOCATIONS_ALLOWED = (
    LOCATION_HUMAN_VILLAGE_OUTSKIRTS,
    LOCATION_HUMAN_VILLAGE_VINEYARDS,
    LOCATION_BAMBOO_FOREST,
    LOCATION_EIENTEI_MANSION,
    LOCATION_RUINS,
    LOCATION_HAKUGYOKUROU_MANSION,
    LOCATION_MORIYA_SHRINE,
)
