__all__ = (
    'LOCATION_ID_BAMBOO_FOREST', 'LOCATION_ID_EIENTEI_MANSION', 'LOCATION_ID_HAKUGYOKUROU_MANSION',
    'LOCATION_ID_HUMAN_VILLAGE_OUTSKIRTS', 'LOCATION_ID_HUMAN_VILLAGE_VINEYARDS', 'LOCATION_ID_MAGIC_FOREST',
    'LOCATION_ID_MISTY_LAKE', 'LOCATION_ID_MORIYA_SHRINE', 'LOCATION_ID_RUINS'
)


LOCATION_ID_HUMAN_VILLAGE_OUTSKIRTS = 1
LOCATION_ID_HUMAN_VILLAGE_VINEYARDS = 2
LOCATION_ID_RUINS = 3
LOCATION_ID_EIENTEI_MANSION = 4
LOCATION_ID_BAMBOO_FOREST = 5
LOCATION_ID_MORIYA_SHRINE = 6
LOCATION_ID_HAKUGYOKUROU_MANSION = 7
LOCATION_ID_MISTY_LAKE = 8
LOCATION_ID_MAGIC_FOREST = 9
