__all__ = (
    'ITEM_FLAG_COSTUME', 'ITEM_FLAG_EDIBLE', 'ITEM_FLAG_HEAD', 'ITEM_FLAG_NPC', 'ITEM_FLAG_SPECIES', 'ITEM_FLAG_WEAPON'
)


ITEM_FLAG_EDIBLE = 1 << 0
ITEM_FLAG_COSTUME = 1 << 1
ITEM_FLAG_HEAD = 1 << 2
ITEM_FLAG_SPECIES = 1 << 3
ITEM_FLAG_WEAPON = 1 << 4
ITEM_FLAG_NPC = 1 << 5
