__all__ = (
    'ITEM_ID_BLUEBERRY', 'ITEM_ID_BLUEFRANKISH', 'ITEM_ID_DEVILCART_OYSTER', 'ITEM_ID_FISHING_ROD',
    'ITEM_ID_FLYKILLER_AMANATA', 'ITEM_ID_PEACH', 'ITEM_ID_STRAWBERRY', 
)


ITEM_ID_STRAWBERRY = 1
ITEM_ID_PEACH = 2
ITEM_ID_BLUEBERRY = 3
ITEM_ID_DEVILCART_OYSTER = 4
ITEM_ID_FLYKILLER_AMANATA = 5
ITEM_ID_FISHING_ROD = 6
ITEM_ID_BLUEFRANKISH = 7
