__all__ = (
    'ITEM_ID_ALICE', 'ITEM_ID_ANGELROOT', 'ITEM_ID_BISHOPHAT', 'ITEM_ID_BLUEBERRY', 'ITEM_ID_BLUEFRANKISH',
    'ITEM_ID_CARROT', 'ITEM_ID_CHIRUNO', 'ITEM_ID_DAI', 'ITEM_ID_DEVILCART_OYSTER', 'ITEM_ID_FISHING_ROD',
    'ITEM_ID_FLYKILLER_AMANITA', 'ITEM_ID_FROG', 'ITEM_ID_GARLIC', 'ITEM_ID_JUNKO', 'ITEM_ID_KOISHI', 'ITEM_ID_MARISA',
    'ITEM_ID_MYSTIA', 'ITEM_ID_ORIN', 'ITEM_ID_PEACH', 'ITEM_ID_SAKUYA', 'ITEM_ID_SCARLET_ONION', 'ITEM_ID_SCISSORS',
    'ITEM_ID_STRAWBERRY', 'ITEM_ID_TEWI'
)

ITEM_ID_STRAWBERRY = 1
ITEM_ID_PEACH = 2
ITEM_ID_BLUEBERRY = 3
ITEM_ID_DEVILCART_OYSTER = 4
ITEM_ID_FLYKILLER_AMANITA = 5
ITEM_ID_FISHING_ROD = 6
ITEM_ID_BLUEFRANKISH = 7
ITEM_ID_CARROT = 8
ITEM_ID_GARLIC = 9
ITEM_ID_SCARLET_ONION = 10
ITEM_ID_MYSTIA = 11
ITEM_ID_SAKUYA = 12
ITEM_ID_MARISA = 13
ITEM_ID_ALICE = 14
ITEM_ID_KOISHI = 15
ITEM_ID_ORIN = 16
ITEM_ID_SCISSORS = 17
ITEM_ID_FROG = 18
ITEM_ID_CHIRUNO = 19
ITEM_ID_DAI = 20
ITEM_ID_ANGELROOT = 21
ITEM_ID_BISHOPHAT = 22
ITEM_ID_JUNKO = 23
ITEM_ID_TEWI = 24
