__all__ = (
    'ITEM_ID_ALICE', 'ITEM_ID_ANGELROOT', 'ITEM_ID_BAMBOO_SHOOT',
    'ITEM_ID_BIG_BRAIDS_OF_THE_HELL_CAT', 'ITEM_ID_BISHOPHAT', 'ITEM_ID_BLUEBERRY',
    'ITEM_ID_BLUEFRANKISH', 'ITEM_ID_BUNNY_SUIT',
    'ITEM_ID_CARROT', 'ITEM_ID_ROGUISH_DRESS_OF_THE_CORPSE_VOYAGER', 'ITEM_ID_ELEGANT_DRESS_OF_THE_CHIEF_MAID',
    'ITEM_ID_CHIRUNO', 'ITEM_ID_DAI',
    'ITEM_ID_DEVILCART_OYSTER', 'ITEM_ID_ELECTROSTATIC_DISCHARGE_PROTECTIVE_COAT',
    'ITEM_ID_FIERY_CHARIOT_OF_THE_RED_EYED_KASHA',
    'ITEM_ID_FISHING_ROD', 'ITEM_ID_FLYKILLER_AMANITA', 'ITEM_ID_FROG', 'ITEM_ID_GARLIC', 'ITEM_ID_JUNKO',
    'ITEM_ID_KINGS_NEW_CLOTHES', 'ITEM_ID_KOISHI', 'ITEM_ID_KOKORO', 'ITEM_ID_MAID_DRESS', 'ITEM_ID_MARISA',
    'ITEM_ID_MYSTIA', 'ITEM_ID_ORIN', 'ITEM_ID_PEACH', 'ITEM_ID_PLUSHIE_BEAR', 'ITEM_ID_RIBBON_BOW', 'ITEM_ID_RULER',
    'ITEM_ID_SAKUYA',
    'ITEM_ID_SCARLET_ONION', 'ITEM_ID_SCISSORS', 'ITEM_ID_STRAW_HAT', 'ITEM_ID_STRAWBERRY', 'ITEM_ID_TEWI',
    'ITEM_ID_TORN_OUT_WING_OF_THE_UNKNOWN_OVEN', 'ITEM_ID_YUKARI', 'ITEM_ID_YUUKA'
)


ITEM_ID_STRAWBERRY = 1
ITEM_ID_PEACH = 2
ITEM_ID_BLUEBERRY = 3
ITEM_ID_DEVILCART_OYSTER = 4
ITEM_ID_FLYKILLER_AMANITA = 5
ITEM_ID_FISHING_ROD = 6
ITEM_ID_BLUEFRANKISH = 7
ITEM_ID_CARROT = 8
ITEM_ID_GARLIC = 9
ITEM_ID_SCARLET_ONION = 10
ITEM_ID_MYSTIA = 11
ITEM_ID_SAKUYA = 12
ITEM_ID_MARISA = 13
ITEM_ID_ALICE = 14
ITEM_ID_KOISHI = 15
ITEM_ID_ORIN = 16
ITEM_ID_SCISSORS = 17
ITEM_ID_FROG = 18
ITEM_ID_CHIRUNO = 19
ITEM_ID_DAI = 20
ITEM_ID_ANGELROOT = 21
ITEM_ID_BISHOPHAT = 22
ITEM_ID_JUNKO = 23
ITEM_ID_TEWI = 24
ITEM_ID_KOKORO = 25
ITEM_ID_RIBBON_BOW = 26
ITEM_ID_STRAW_HAT = 27
ITEM_ID_RULER = 28
ITEM_ID_YUKARI = 29
ITEM_ID_YUUKA = 30
ITEM_ID_BAMBOO_SHOOT = 31
ITEM_ID_PLUSHIE_BEAR = 32
ITEM_ID_KINGS_NEW_CLOTHES = 33
ITEM_ID_MAID_DRESS = 34
ITEM_ID_ELEGANT_DRESS_OF_THE_CHIEF_MAID = 35
ITEM_ID_TORN_OUT_WING_OF_THE_UNKNOWN_OVEN = 36
ITEM_ID_BUNNY_SUIT = 37
ITEM_ID_ELECTROSTATIC_DISCHARGE_PROTECTIVE_COAT = 38
ITEM_ID_BIG_BRAIDS_OF_THE_HELL_CAT = 39
ITEM_ID_FIERY_CHARIOT_OF_THE_RED_EYED_KASHA = 40
ITEM_ID_ROGUISH_DRESS_OF_THE_CORPSE_VOYAGER = 41
