__all__ = ()

from hata import BUILTIN_EMOJIS

from ..relationships_core import (
    RELATIONSHIP_TYPE_MAMA, RELATIONSHIP_TYPE_MISTRESS, RELATIONSHIP_TYPE_SISTER_BIG, RELATIONSHIP_TYPE_WAIFU
)


ACTION_NAME_UNKNOWN = 'pudding'


RELATIONSHIP_REQUEST_CREATABLE = {
    'marry': RELATIONSHIP_TYPE_WAIFU,
    'blood-pact' : RELATIONSHIP_TYPE_SISTER_BIG,
    'adopt': RELATIONSHIP_TYPE_MAMA,
    'hire': RELATIONSHIP_TYPE_MISTRESS,
}

PAGE_SIZE_DEFAULT = 10


EMOJI_PAGE_DECREMENT = BUILTIN_EMOJIS['arrow_left']
EMOJI_PAGE_INCREMENT = BUILTIN_EMOJIS['arrow_right']
EMOJI_CLOSE = BUILTIN_EMOJIS['x']


RELATIONSHIP_LISTING_MODE_LEGACY = 0
RELATIONSHIP_LISTING_MODE_LONG = 1
RELATIONSHIP_LISTING_MODE_WIDE = 2

RELATIONSHIP_LISTING_MODE_DEFAULT = RELATIONSHIP_LISTING_MODE_WIDE
