__all__ = ()

from ..relationships_core import (
    RELATIONSHIP_TYPE_MAMA, RELATIONSHIP_TYPE_MISTRESS, RELATIONSHIP_TYPE_SISTER_BIG, RELATIONSHIP_TYPE_WAIFU
)


ACTION_NAME_UNKNOWN = 'pudding'


RELATIONSHIP_REQUEST_CREATABLE = {
    'marry': RELATIONSHIP_TYPE_WAIFU,
    'blood-pact' : RELATIONSHIP_TYPE_SISTER_BIG,
    'adopt': RELATIONSHIP_TYPE_MAMA,
    'hire': RELATIONSHIP_TYPE_MISTRESS,
}
