__all__ = ()

from ..relationships_core import (
    RELATIONSHIP_TYPE_AUNTIE, RELATIONSHIP_TYPE_CONNECTION_MODIFIER_SHIFT_ANCESTORSHIP,
    RELATIONSHIP_TYPE_CONNECTION_MODIFIER_SHIFT_EMPLOYMENTSHIP, RELATIONSHIP_TYPE_CONNECTION_MODIFIER_SHIFT_SISTERSHIP,
    RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_HALF, RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_IN_LAW,
    RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_NONE, RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_STEP,
    RELATIONSHIP_TYPE_CO_WORKER, RELATIONSHIP_TYPE_DAUGHTER, RELATIONSHIP_TYPE_GRANDDAUGHTER, RELATIONSHIP_TYPE_GRANNY,
    RELATIONSHIP_TYPE_MAID, RELATIONSHIP_TYPE_MAMA, RELATIONSHIP_TYPE_MISTRESS, RELATIONSHIP_TYPE_NANNY,
    RELATIONSHIP_TYPE_NIECE, RELATIONSHIP_TYPE_SISTER_BIG, RELATIONSHIP_TYPE_SISTER_LIL, RELATIONSHIP_TYPE_TEA_FRIEND,
    RELATIONSHIP_TYPE_UNSET, RELATIONSHIP_TYPE_WAIFU, RELATIONSHIP_TYPE_YOUNG_MISTRESS
)


RELATIONSHIP_LISTING_PAGE_SIZE = 20
RELATIONSHIP_LISTING_PAGE_BREAK_GROUP_IF_LESS = 3


RELATIONSHIP_TYPE_MASK_ORDER = (
    RELATIONSHIP_TYPE_WAIFU,
    
    RELATIONSHIP_TYPE_SISTER_BIG,
    RELATIONSHIP_TYPE_SISTER_LIL,
    RELATIONSHIP_TYPE_MAMA,
    RELATIONSHIP_TYPE_GRANNY,
    RELATIONSHIP_TYPE_AUNTIE,
    RELATIONSHIP_TYPE_DAUGHTER,
    RELATIONSHIP_TYPE_GRANDDAUGHTER,
    RELATIONSHIP_TYPE_NIECE,
    
    RELATIONSHIP_TYPE_MISTRESS,
    RELATIONSHIP_TYPE_YOUNG_MISTRESS,
    RELATIONSHIP_TYPE_MAID,
    RELATIONSHIP_TYPE_NANNY,
    
    RELATIONSHIP_TYPE_TEA_FRIEND,
    RELATIONSHIP_TYPE_CO_WORKER,
        
    RELATIONSHIP_TYPE_UNSET,
)


RELATIONSHIP_TYPE_MODIFIER_SHIFTS = {
    RELATIONSHIP_TYPE_SISTER_BIG : RELATIONSHIP_TYPE_CONNECTION_MODIFIER_SHIFT_SISTERSHIP,
    RELATIONSHIP_TYPE_SISTER_LIL : RELATIONSHIP_TYPE_CONNECTION_MODIFIER_SHIFT_SISTERSHIP,
    
    RELATIONSHIP_TYPE_MAMA : RELATIONSHIP_TYPE_CONNECTION_MODIFIER_SHIFT_ANCESTORSHIP,
    RELATIONSHIP_TYPE_DAUGHTER : RELATIONSHIP_TYPE_CONNECTION_MODIFIER_SHIFT_ANCESTORSHIP,
    
    RELATIONSHIP_TYPE_MISTRESS : RELATIONSHIP_TYPE_CONNECTION_MODIFIER_SHIFT_EMPLOYMENTSHIP,
    RELATIONSHIP_TYPE_MAID : RELATIONSHIP_TYPE_CONNECTION_MODIFIER_SHIFT_EMPLOYMENTSHIP,
}


RELATIONSHIP_TYPE_MODIFIERS_ORDER_NONE = (
    RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_NONE,
)


RELATIONSHIP_TYPE_MODIFIERS_ORDER = (
    RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_NONE,
    RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_HALF,
    RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_STEP,
    RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_IN_LAW,
)


RELATIONSHIP_CONNECTION_TYPE_NAMES = {
    RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_HALF : 'half',
    RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_STEP : 'step',
    RELATIONSHIP_TYPE_CONNECTION_MODIFIER_TYPE_IN_LAW : 'in law',
}


RELATIONSHIP_TITLES = {
    RELATIONSHIP_TYPE_WAIFU : ('Waifu', 'Waifus'),
    RELATIONSHIP_TYPE_SISTER_BIG : ('Big sister', 'Big sisters'),
    RELATIONSHIP_TYPE_SISTER_LIL : ('Lil sister', 'Lil sisters'),
    RELATIONSHIP_TYPE_MAMA : ('Mama', 'Mamas'),
    RELATIONSHIP_TYPE_DAUGHTER : ('Daughter', 'Daughters'),
    RELATIONSHIP_TYPE_MISTRESS : ('Mistress', 'Mistresses'),
    RELATIONSHIP_TYPE_MAID : ('Maid', 'Maids'),
    RELATIONSHIP_TYPE_UNSET : ('Unset', 'Unset'),
    RELATIONSHIP_TYPE_AUNTIE : ('Auntie', 'Aunties'),
    RELATIONSHIP_TYPE_NIECE : ('Niece', 'Nieces'),
    RELATIONSHIP_TYPE_CO_WORKER : ('Co-worker', 'Co-workers'),
    RELATIONSHIP_TYPE_GRANNY : ('Granny', 'Grannies'),
    RELATIONSHIP_TYPE_GRANDDAUGHTER : ('Granddaughter', 'Granddaughters'),
    RELATIONSHIP_TYPE_YOUNG_MISTRESS : ('Young mistress', 'Young mistresses'),
    RELATIONSHIP_TYPE_TEA_FRIEND : ('Tea friend', 'Tea friends'),
    RELATIONSHIP_TYPE_NANNY : ('Nanny', 'Nannies'),
}
