__all__ = ()

from .calendar_event import CalendarEvent
from .constants import (
    COLOR_CODE_BLACK, COLOR_CODE_BLUE, COLOR_CODE_GREEN, COLOR_CODE_ORANGE, COLOR_CODE_PINK, COLOR_CODE_RED,
    COLOR_CODE_TEAL, COLOR_CODE_WHITE
)


CALENDAR_EVENTS = (
    CalendarEvent( 1,  6,      'Reimu',    COLOR_CODE_RED),
    CalendarEvent( 1,  9,        'Iku',   COLOR_CODE_PINK),
    CalendarEvent( 1, 10,     'Momiji',  COLOR_CODE_WHITE),
    CalendarEvent( 2,  3,      'Yuugi', COLOR_CODE_ORANGE),
    CalendarEvent( 2, 10,       'Futo',   COLOR_CODE_TEAL),
    CalendarEvent( 2, 18,    'Mamizou',  COLOR_CODE_GREEN),
    CalendarEvent( 3,  7,      'Sanae',  COLOR_CODE_GREEN),
    CalendarEvent( 3,  9,     'Sakuya',   COLOR_CODE_TEAL),
    CalendarEvent( 3, 17,     'Yuyuko',   COLOR_CODE_PINK),
    CalendarEvent( 4,  4,       'Tewi',   COLOR_CODE_PINK),
    CalendarEvent( 4,  6,      'Youmu',  COLOR_CODE_WHITE),
    CalendarEvent( 4, 10,     'Parsee', COLOR_CODE_ORANGE),
    CalendarEvent( 4, 27,   'Medicine',    COLOR_CODE_RED),
    CalendarEvent( 4, 28,    'Shizuha', COLOR_CODE_ORANGE),
    CalendarEvent( 4, 30,      'Keine',   COLOR_CODE_TEAL),
    CalendarEvent( 5,  5,     'Kokoro',   COLOR_CODE_PINK),
    CalendarEvent( 5, 14,     'Koishi',  COLOR_CODE_GREEN),
    CalendarEvent( 5, 15,    'Meiling',    COLOR_CODE_RED),
    CalendarEvent( 5, 16,     'Marisa',  COLOR_CODE_BLACK),
    CalendarEvent( 6,  3,     'Murasa',  COLOR_CODE_WHITE),
    CalendarEvent( 6,  4,    'Wriggle',  COLOR_CODE_GREEN),
    CalendarEvent( 6,  5,      'Junko', COLOR_CODE_ORANGE),
    CalendarEvent( 6,  6,  'Sekibanki',    COLOR_CODE_RED),
    CalendarEvent( 6,  9,  'Patchouli',   COLOR_CODE_PINK),
    CalendarEvent( 6, 11,     'Kogasa',   COLOR_CODE_TEAL),
    CalendarEvent( 6, 22,       'Eiki',  COLOR_CODE_GREEN),
    CalendarEvent( 6, 24,        'Nue',  COLOR_CODE_BLACK),
    CalendarEvent( 7,  4,    'Flandre', COLOR_CODE_ORANGE),
    CalendarEvent( 7,  6,     'Lyrica',    COLOR_CODE_RED),
    CalendarEvent( 7,  7,      'Rumia',    COLOR_CODE_RED),
    CalendarEvent( 7, 14,      'Yuuka',  COLOR_CODE_GREEN),
    CalendarEvent( 7, 16,      'Alice',   COLOR_CODE_BLUE),
    CalendarEvent( 7, 20,     'Nazrin',  COLOR_CODE_BLACK),
    CalendarEvent( 8,  3,     'Kanako',    COLOR_CODE_RED),
    CalendarEvent( 8,  7,     'Yamame', COLOR_CODE_ORANGE),
    CalendarEvent( 8,  8,      'Eirin',   COLOR_CODE_BLUE),
    CalendarEvent( 8,  9,     'Doremy',   COLOR_CODE_PINK),
    CalendarEvent( 8, 10,       'Hina',  COLOR_CODE_GREEN),
    CalendarEvent( 8, 12,     'Lunasa',  COLOR_CODE_BLACK),
    CalendarEvent( 9,  6,     'Suwako',  COLOR_CODE_WHITE),
    CalendarEvent( 9,  8,     'Kaguya',   COLOR_CODE_PINK),
    CalendarEvent( 9,  9,    'Chiruno',   COLOR_CODE_BLUE),
    CalendarEvent( 9, 10,    'Ichirin',   COLOR_CODE_BLUE),
    CalendarEvent(10,  4,     'Tenshi',   COLOR_CODE_BLUE),
    CalendarEvent(10,  9,        'Aya',  COLOR_CODE_BLACK),
    CalendarEvent(10, 10,       'Chen',    COLOR_CODE_RED),
    CalendarEvent(10, 25,       'Soga',  COLOR_CODE_GREEN),
    CalendarEvent(10, 26,     'Utsuho',  COLOR_CODE_WHITE),
    CalendarEvent(11, 10,     'Kisume',   COLOR_CODE_TEAL),
    CalendarEvent(12, 12,   'Byakuren',   COLOR_CODE_PINK),
    CalendarEvent(12, 22,     'Yukari',   COLOR_CODE_BLUE),
)
