__all__ = (
    'TOUHOU_ACTION_FEED', 'TOUHOU_ACTION_FLUFF', 'TOUHOU_ACTION_HUG', 'TOUHOU_ACTION_KISS', 'TOUHOU_ACTION_KON',
    'TOUHOU_ACTION_LAP_SLEEP', 'TOUHOU_ACTION_LICK', 'TOUHOU_ACTION_LIKE', 'TOUHOU_ACTION_PAT', 'TOUHOU_ACTION_PEG',
    'TOUHOU_ACTION_POCKY_KISS', 'TOUHOU_ACTION_POCKY_KISS_SELF', 'TOUHOU_ACTION_POKE', 'TOUHOU_ACTION_STARE',
    'TOUHOU_ACTION_TICKLE',
)

from .constants import (
    ACTION_TAG_FEED, ACTION_TAG_FLUFF, ACTION_TAG_HUG, ACTION_TAG_KISS, ACTION_TAG_KON, ACTION_TAG_LAP_SLEEP,
    ACTION_TAG_LICK, ACTION_TAG_LIKE, ACTION_TAG_PAT, ACTION_TAG_PEG, ACTION_TAG_POCKY,
    ACTION_TAG_POCKY_SELF, ACTION_TAG_POKE, ACTION_TAG_STARE, ACTION_TAG_TICKLE
)
from .listing import TOUHOU_ACTION_ALL


TOUHOU_ACTION_FEED = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_FEED)
TOUHOU_ACTION_FLUFF = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_FLUFF)
TOUHOU_ACTION_HUG = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_HUG)
TOUHOU_ACTION_KISS = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_KISS)
TOUHOU_ACTION_KON = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_KON)
TOUHOU_ACTION_LAP_SLEEP = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_LAP_SLEEP)
TOUHOU_ACTION_LICK = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_LICK)
TOUHOU_ACTION_LIKE = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_LIKE)
TOUHOU_ACTION_PAT = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_PAT)
TOUHOU_ACTION_PEG = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_PEG)
TOUHOU_ACTION_POCKY_KISS = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_POCKY)
TOUHOU_ACTION_POCKY_KISS_SELF = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_POCKY_SELF)
TOUHOU_ACTION_POKE = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_POKE)
TOUHOU_ACTION_STARE = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_STARE)
TOUHOU_ACTION_TICKLE = TOUHOU_ACTION_ALL.create_action_subset(ACTION_TAG_TICKLE)
