__all__ = ()

ICON_KIND_ICON = 1
ICON_KIND_BANNER = 2
ICON_KIND_DISCOVERY_SPLASH = 3
ICON_KIND_INVITE_SPLASH = 4


ICON_KINDS = {
    'icon': ICON_KIND_ICON,
    'banner': ICON_KIND_BANNER,
    'discovery-splash': ICON_KIND_DISCOVERY_SPLASH,
    'invite-splash': ICON_KIND_INVITE_SPLASH,
}

ICON_KINDS_REVERSED = {value: key for key, value in ICON_KINDS.items()}


CUSTOM_ID_GUILD_ICON = f'guild.icon.{ICON_KIND_ICON}'
CUSTOM_ID_GUILD_BANNER = f'guild.icon.{ICON_KIND_BANNER}'
CUSTOM_ID_GUILD_DISCOVERY_SPLASH = f'guild.icon.{ICON_KIND_DISCOVERY_SPLASH}'
CUSTOM_ID_GUILD_INVITE_SPLASH = f'guild.icon.{ICON_KIND_INVITE_SPLASH}'
