__all__ = ()

from ...bot_utils.constants import ROLE__SUPPORT__ELEVATED, ROLE__SUPPORT__HEART_BOOST, ROLE__SUPPORT__NSFW_ACCESS


NSFW_ACCESS_REQUIRED_BALANCE = 8000
ELEVATED_REQUIRED_BALANCE = 12000
HEART_BOOST_REQUIRED_BALANCE = 100000


PURCHASABLE_ROLES = {
    ROLE__SUPPORT__NSFW_ACCESS.id: (ROLE__SUPPORT__NSFW_ACCESS, NSFW_ACCESS_REQUIRED_BALANCE),
    ROLE__SUPPORT__ELEVATED.id: (ROLE__SUPPORT__ELEVATED, ELEVATED_REQUIRED_BALANCE),
    ROLE__SUPPORT__HEART_BOOST.id: (ROLE__SUPPORT__HEART_BOOST, HEART_BOOST_REQUIRED_BALANCE),
}

ROLE_CHOICES = [
    (f'Horny ({NSFW_ACCESS_REQUIRED_BALANCE})', format(ROLE__SUPPORT__NSFW_ACCESS.id, 'x')),
    (f'Orin\'s Workcarrier ({ELEVATED_REQUIRED_BALANCE})', format(ROLE__SUPPORT__ELEVATED.id, 'x')),
    (f'Koishi enjoyer ({HEART_BOOST_REQUIRED_BALANCE})', format(ROLE__SUPPORT__HEART_BOOST.id, 'x')),
]
