__all__ = ('PURCHASABLE_ROLES', 'ROLE_CHOICES',)

from ...bot_utils.constants import ROLE__SUPPORT__ELEVATED, ROLE__SUPPORT__HEART_BOOST, ROLE__SUPPORT__NSFW_ACCESS


NSFW_ACCESS_REQUIRED_BALANCE = 8000
ELEVATED_REQUIRED_BALANCE = 12000
HEART_BOOST_REQUIRED_BALANCE = 100000


NSFW_ACCESS_IDENTIFIER = '0'
ELEVATED_IDENTIFIER = '1'
HEART_BOOST_IDENTIFIER = '2'

PURCHASABLE_ROLES = {
    NSFW_ACCESS_IDENTIFIER: (ROLE__SUPPORT__NSFW_ACCESS, NSFW_ACCESS_REQUIRED_BALANCE),
    ELEVATED_IDENTIFIER: (ROLE__SUPPORT__ELEVATED, ELEVATED_REQUIRED_BALANCE),
    HEART_BOOST_IDENTIFIER: (ROLE__SUPPORT__HEART_BOOST, HEART_BOOST_REQUIRED_BALANCE),
}

ROLE_CHOICES = [
    (f'Horny ({NSFW_ACCESS_REQUIRED_BALANCE})', NSFW_ACCESS_IDENTIFIER),
    (f'Orin\'s Workcarrier ({ELEVATED_REQUIRED_BALANCE})', ELEVATED_IDENTIFIER),
    (f'Koishi enjoyer ({HEART_BOOST_REQUIRED_BALANCE})', HEART_BOOST_IDENTIFIER),
]
