__all__ = (
    'PREFERRED_IMAGE_SOURCE_NAMES', 'PREFERRED_IMAGE_SOURCE_NONE', 'PREFERRED_IMAGE_SOURCE_TOUHOU',
    'PREFERRED_IMAGE_SOURCE_WAIFU_PICS', 'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_BY_WAIFU_DISABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_BY_WAIFU_ENABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_REMINDER_DISABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_REMINDER_ENABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_PROPOSAL_DISABLE', 'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_PROPOSAL_ENABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_VOTE_DISABLE', 'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_VOTE_ENABLE', 
)

# preference / client
PREFERRED_CLIENT_NAME_DEFAULT = 'unset'

# preference / source
PREFERRED_IMAGE_SOURCE_NONE = 0
PREFERRED_IMAGE_SOURCE_WAIFU_PICS = 1
PREFERRED_IMAGE_SOURCE_TOUHOU = 2

PREFERRED_IMAGE_SOURCE_NAME_DEFAULT = 'unknown'

PREFERRED_IMAGE_SOURCE_NAME_NONE = 'none'
PREFERRED_IMAGE_SOURCE_NAME_WAIFU_PICS = 'waifu-pics'
PREFERRED_IMAGE_SOURCE_NAME_TOUHOU = 'touhou'

PREFERRED_IMAGE_SOURCE_NAMES = {
    PREFERRED_IMAGE_SOURCE_NONE: PREFERRED_IMAGE_SOURCE_NAME_NONE,
    PREFERRED_IMAGE_SOURCE_WAIFU_PICS: PREFERRED_IMAGE_SOURCE_NAME_WAIFU_PICS,
    PREFERRED_IMAGE_SOURCE_TOUHOU: PREFERRED_IMAGE_SOURCE_NAME_TOUHOU,
}

# notification
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_BY_WAIFU_ENABLE = 'user_settings.notification_daily_by_waifu.enable'
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_BY_WAIFU_DISABLE = 'user_settings.notification_daily_by_waifu.disable'

USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_REMINDER_ENABLE = 'user_settings.notification_daily_reminder.enable'
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_REMINDER_DISABLE = 'user_settings.notification_daily_reminder.disable'

USER_SETTINGS_CUSTOM_ID_NOTIFICATION_PROPOSAL_ENABLE = 'user_settings.notification_proposal.enable'
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_PROPOSAL_DISABLE = 'user_settings.notification_proposal.disable'

USER_SETTINGS_CUSTOM_ID_NOTIFICATION_VOTE_ENABLE = 'user_settings.notification_vote.enable'
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_VOTE_DISABLE = 'user_settings.notification_vote.disable'
