__all__ = (
    'PREFERRED_IMAGE_SOURCE_NAME_DEFAULT', 'PREFERRED_IMAGE_SOURCE_NAMES', 'PREFERRED_IMAGE_SOURCE_NONE',
    'PREFERRED_IMAGE_SOURCE_TOUHOU', 'PREFERRED_IMAGE_SOURCE_WAIFU_PICS',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_ADVENTURE_RECOVERY_OVER_DISABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_ADVENTURE_RECOVERY_OVER_ENABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_BY_WAIFU_DISABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_BY_WAIFU_ENABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_REMINDER_DISABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_REMINDER_ENABLE', 'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_GIFT_DISABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_GIFT_ENABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_MARKET_PLACE_ITEM_FINALISATION_DISABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_MARKET_PLACE_ITEM_FINALISATION_ENABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_PROPOSAL_DISABLE', 'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_PROPOSAL_ENABLE',
    'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_VOTE_DISABLE', 'USER_SETTINGS_CUSTOM_ID_NOTIFICATION_VOTE_ENABLE',
    'USER_SETTINGS_FEATURE_FLAG_DEFAULT', 'USER_SETTINGS_FEATURE_FLAG_DEFAULT_MARKET_PLACE_INBOX',
    'USER_SETTINGS_FEATURE_FLAG_SHIFT_MARKET_PLACE_INBOX', 'USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT',
    'USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_ADVENTURE_RECOVERY_OVER',
    'USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_DAILY_BY_WAIFU', 'USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_DAILY_REMINDER',
    'USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_GIFT',
    'USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_MARKET_PLACE_ITEM_FINALISATION',
    'USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_PROPOSAL', 'USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_VOTE',
    'USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_ADVENTURE_RECOVERY_OVER',
    'USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_DAILY_BY_WAIFU', 'USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_DAILY_REMINDER',
    'USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_GIFT',
    'USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_MARKET_PLACE_ITEM_FINALISATION',
    'USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_PROPOSAL', 'USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_VOTE'
)

# preference / client
PREFERRED_CLIENT_NAME_DEFAULT = 'unset'

# preference / source
PREFERRED_IMAGE_SOURCE_NONE = 0
PREFERRED_IMAGE_SOURCE_WAIFU_PICS = 1
PREFERRED_IMAGE_SOURCE_TOUHOU = 2

PREFERRED_IMAGE_SOURCE_NAME_DEFAULT = 'unknown'

PREFERRED_IMAGE_SOURCE_NAME_NONE = 'none'
PREFERRED_IMAGE_SOURCE_NAME_WAIFU_PICS = 'waifu-pics'
PREFERRED_IMAGE_SOURCE_NAME_TOUHOU = 'touhou'

PREFERRED_IMAGE_SOURCE_NAMES = {
    PREFERRED_IMAGE_SOURCE_NONE: PREFERRED_IMAGE_SOURCE_NAME_NONE,
    PREFERRED_IMAGE_SOURCE_WAIFU_PICS: PREFERRED_IMAGE_SOURCE_NAME_WAIFU_PICS,
    PREFERRED_IMAGE_SOURCE_TOUHOU: PREFERRED_IMAGE_SOURCE_NAME_TOUHOU,
}

# notification
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_ADVENTURE_RECOVERY_OVER_ENABLE = 'user_settings.adventure_recovery_over.enable'
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_ADVENTURE_RECOVERY_OVER_DISABLE = 'user_settings.adventure_recovery_over.disable'

USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_BY_WAIFU_ENABLE = 'user_settings.notification_daily_by_waifu.enable'
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_BY_WAIFU_DISABLE = 'user_settings.notification_daily_by_waifu.disable'

USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_REMINDER_ENABLE = 'user_settings.notification_daily_reminder.enable'
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_DAILY_REMINDER_DISABLE = 'user_settings.notification_daily_reminder.disable'

USER_SETTINGS_CUSTOM_ID_NOTIFICATION_GIFT_ENABLE = 'user_settings.notification_gift.enable'
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_GIFT_DISABLE = 'user_settings.notification_gift.disable'

USER_SETTINGS_CUSTOM_ID_NOTIFICATION_MARKET_PLACE_ITEM_FINALISATION_ENABLE = (
    'user_settings.market_place_item_finalisation.enable'
)
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_MARKET_PLACE_ITEM_FINALISATION_DISABLE = (
    'user_settings.market_place_item_finalisation.disable'
)

USER_SETTINGS_CUSTOM_ID_NOTIFICATION_PROPOSAL_ENABLE = 'user_settings.notification_proposal.enable'
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_PROPOSAL_DISABLE = 'user_settings.notification_proposal.disable'

USER_SETTINGS_CUSTOM_ID_NOTIFICATION_VOTE_ENABLE = 'user_settings.notification_vote.enable'
USER_SETTINGS_CUSTOM_ID_NOTIFICATION_VOTE_DISABLE = 'user_settings.notification_vote.disable'


USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_ADVENTURE_RECOVERY_OVER = 0
USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_DAILY_BY_WAIFU = 1
USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_DAILY_REMINDER = 2
USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_GIFT = 3
USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_MARKET_PLACE_ITEM_FINALISATION = 4
USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_PROPOSAL = 5
USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_VOTE = 6


USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_ADVENTURE_RECOVERY_OVER = 0
USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_DAILY_BY_WAIFU = 1
USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_DAILY_REMINDER = 0
USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_GIFT = 1
USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_MARKET_PLACE_ITEM_FINALISATION = 0
USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_PROPOSAL = 1
USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_VOTE = 1


USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT = (
    (USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_ADVENTURE_RECOVERY_OVER << USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_ADVENTURE_RECOVERY_OVER) |
    (USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_DAILY_BY_WAIFU << USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_DAILY_BY_WAIFU) |
    (USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_DAILY_REMINDER << USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_DAILY_REMINDER) |
    (USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_GIFT << USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_GIFT) |
    (USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_MARKET_PLACE_ITEM_FINALISATION << USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_MARKET_PLACE_ITEM_FINALISATION) |
    (USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_PROPOSAL << USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_PROPOSAL) |
    (USER_SETTINGS_NOTIFICATION_FLAG_DEFAULT_VOTE << USER_SETTINGS_NOTIFICATION_FLAG_SHIFT_VOTE)
)


USER_SETTINGS_FEATURE_FLAG_SHIFT_MARKET_PLACE_INBOX = 1

USER_SETTINGS_FEATURE_FLAG_DEFAULT_MARKET_PLACE_INBOX = 1

USER_SETTINGS_FEATURE_FLAG_DEFAULT = (
    (USER_SETTINGS_FEATURE_FLAG_DEFAULT_MARKET_PLACE_INBOX << USER_SETTINGS_FEATURE_FLAG_SHIFT_MARKET_PLACE_INBOX)
)
