__all__ = ()

from hata import BUILTIN_EMOJIS


BROKEN_QUEST_DESCRIPTION = 'Broken quest'

EMOJI_PAGE_PREVIOUS = BUILTIN_EMOJIS['arrow_left']
EMOJI_PAGE_NEXT = BUILTIN_EMOJIS['arrow_right']
EMOJI_REFRESH = BUILTIN_EMOJIS['arrows_counterclockwise']
EMOJI_BACK = BUILTIN_EMOJIS['leftwards_arrow_with_hook']

PAGE_SIZE = 10
REQUIREMENT_PAGE_SIZE = 6


LINKED_QUEST_BACK_DIRECT_LOCATION_QUEST = 0
LINKED_QUEST_BACK_DIRECT_LOCATION_SELECT_REQUIREMENT = 1
LINKED_QUEST_BACK_DIRECT_LOCATION_SELECT_ITEM_TOP = 2
LINKED_QUEST_BACK_DIRECT_LOCATION_SELECT_ITEM_NESTED = 3
