__all__ = (
    'USER_STATS_CACHE', 'USER_STAT_NAME_FULL_BEDROOM', 'USER_STAT_NAME_FULL_CHARM', 'USER_STAT_NAME_FULL_CUTENESS',
    'USER_STAT_NAME_FULL_HOUSEWIFE', 'USER_STAT_NAME_FULL_LOYALTY',
)

from collections import OrderedDict
from scarletio import WeakValueDictionary

USER_STATS = WeakValueDictionary()
USER_STATS_CACHE = OrderedDict()
USER_STATS_CACHE_SIZE = 100
USER_STATS_SAVE_TASKS = {}
USER_STATS_QUERY_TASKS = {}


USER_STAT_NAME_FULL_HOUSEWIFE = 'Housewife-capabilities'
USER_STAT_NAME_FULL_CUTENESS = 'Cuteness'
USER_STAT_NAME_FULL_BEDROOM = 'Bedroom-skills'
USER_STAT_NAME_FULL_CHARM = 'Charm'
USER_STAT_NAME_FULL_LOYALTY = 'Loyalty'

USER_STAT_NAME_SHORT_HOUSEWIFE = 'housewife'
USER_STAT_NAME_SHORT_CUTENESS = 'cuteness'
USER_STAT_NAME_SHORT_BEDROOM = 'bedroom'
USER_STAT_NAME_SHORT_CHARM = 'charm'
USER_STAT_NAME_SHORT_LOYALTY = 'loyalty'
