__all__ = (
    'USER_STAT_NAME_FULL_BEDROOM', 'USER_STAT_NAME_FULL_CHARM', 'USER_STAT_NAME_FULL_CUTENESS',
    'USER_STAT_NAME_FULL_HOUSEWIFE', 'USER_STAT_NAME_FULL_LOYALTY',
)

from collections import OrderedDict


STATS_CACHE = OrderedDict()
STATS_CACHE_SIZE_MAX = 100


USER_STAT_NAME_FULL_HOUSEWIFE = 'Housewife capabilities'
USER_STAT_NAME_FULL_CUTENESS = 'cuteness'
USER_STAT_NAME_FULL_BEDROOM = 'bedroom skills'
USER_STAT_NAME_FULL_CHARM = 'charm'
USER_STAT_NAME_FULL_LOYALTY = 'loyalty'

USER_STAT_NAME_SHORT_HOUSEWIFE = 'housewife'
USER_STAT_NAME_SHORT_CUTENESS = 'cuteness'
USER_STAT_NAME_SHORT_BEDROOM = 'bedroom'
USER_STAT_NAME_SHORT_CHARM = 'charm'
USER_STAT_NAME_SHORT_LOYALTY = 'loyalty'
